export const data = [
  {
    color: "Turquoise",
    name: "Oliviero O' Mahony",
    image: "https://robohash.org/autseddolores.png?size=100x100&set=set1",
    hex_color: "#e1e4c2",
    money: "$580.24",
    mobile: "Android 4.4.2",
  },
  {
    color: "Maroon",
    name: "Nigel Colwell",
    image: "https://robohash.org/quosdictaid.png?size=100x100&set=set1",
    hex_color: "#eb7015",
    money: "$606.12",
    mobile: "Android 4.2, up to 4.4",
  },
  {
    color: "Teal",
    name: "Bonnibelle Wholesworth",
    image: "https://robohash.org/nequeevenieteaque.png?size=100x100&set=set1",
    hex_color: "#32e9a5",
    money: "$895.56",
    mobile: "Feature phone",
  },
  {
    color: "Aquamarine",
    name: "Madeleine Pilkinton",
    image:
      "https://robohash.org/dolorlaboremolestiae.png?size=100x100&set=set1",
    hex_color: "#4267b6",
    money: "$82.93",
    mobile: "Android 2.3",
  },
  {
    color: "Goldenrod",
    name: "Rosanne Yeldham",
    image: "https://robohash.org/autveldolore.png?size=100x100&set=set1",
    hex_color: "#dcafe8",
    money: "$93.58",
    mobile: "Feature phone",
  },
  {
    color: "Violet",
    name: "Henderson Gravenor",
    image: "https://robohash.org/utiddeserunt.png?size=100x100&set=set1",
    hex_color: "#1af4d9",
    money: "$35.40",
    mobile: "KaiOS",
  },
  {
    color: "Blue",
    name: "Denny Worton",
    image: "https://robohash.org/eumquinon.png?size=100x100&set=set1",
    hex_color: "#9f8461",
    money: "$481.38",
    mobile: "Android 4.2",
  },
  {
    color: "Khaki",
    name: "Sibbie Marr",
    image:
      "https://robohash.org/placeatblanditiisvel.png?size=100x100&set=set1",
    hex_color: "#0c5e16",
    money: "$460.62",
    mobile: "Android 7.1.1",
  },
  {
    color: "Teal",
    name: "Shannen Windebank",
    image: "https://robohash.org/accusantiumutest.png?size=100x100&set=set1",
    hex_color: "#b69804",
    money: "$346.79",
    mobile: "Feature phone",
  },
  {
    color: "Turquoise",
    name: "Germain Allbon",
    image:
      "https://robohash.org/nobisvoluptatesaccusantium.png?size=100x100&set=set1",
    hex_color: "#ebbf61",
    money: "$29.56",
    mobile: "Feature phone",
  },
  {
    color: "Red",
    name: "Cinderella Paolillo",
    image: "https://robohash.org/utnihilratione.png?size=100x100&set=set1",
    hex_color: "#002602",
    money: "$644.33",
    mobile: "Feature phone",
  },
  {
    color: "Fuscia",
    name: "Heda Slobom",
    image: "https://robohash.org/explicaboeaqueomnis.png?size=100x100&set=set1",
    hex_color: "#6d7029",
    money: "$621.42",
    mobile: "Android 4.4.2",
  },
  {
    color: "Indigo",
    name: "Remy Rohlfing",
    image: "https://robohash.org/utsuscipitfacere.png?size=100x100&set=set1",
    hex_color: "#85ee07",
    money: "$820.11",
    mobile: "Feature phone",
  },
  {
    color: "Blue",
    name: "Ilise Tommen",
    image: "https://robohash.org/sedabet.png?size=100x100&set=set1",
    hex_color: "#89b699",
    money: "$288.52",
    mobile: "Feature phone",
  },
  {
    color: "Orange",
    name: "Ive Hegges",
    image: "https://robohash.org/officiaautemab.png?size=100x100&set=set1",
    hex_color: "#6d0981",
    money: "$622.47",
    mobile: "Android 8.1, ColorOS 5.2",
  },
  {
    color: "Turquoise",
    name: "Boigie Choudhury",
    image:
      "https://robohash.org/essevoluptatummaxime.png?size=100x100&set=set1",
    hex_color: "#aba867",
    money: "$683.16",
    mobile: "Android 2.3, Sense UI 3.5",
  },
  {
    color: "Mauv",
    name: "Orton Truce",
    image:
      "https://robohash.org/autporrovoluptatibus.png?size=100x100&set=set1",
    hex_color: "#f3e147",
    money: "$284.63",
    mobile: "Android 9.0, MIUI 10",
  },
  {
    color: "Green",
    name: "Skippy Capron",
    image: "https://robohash.org/enimullamquo.png?size=100x100&set=set1",
    hex_color: "#42e634",
    money: "$797.54",
    mobile: "Danger 3.0",
  },
  {
    color: "Violet",
    name: "Ninette Joules",
    image:
      "https://robohash.org/eosquisquamvoluptatem.png?size=100x100&set=set1",
    hex_color: "#253fac",
    money: "$137.26",
    mobile: "Feature phone",
  },
  {
    color: "Orange",
    name: "Jule Kardos-Stowe",
    image: "https://robohash.org/sedquiomnis.png?size=100x100&set=set1",
    hex_color: "#7555f7",
    money: "$47.44",
    mobile: "Android 4.4.2",
  },
  {
    color: "Red",
    name: "Samson Autie",
    image:
      "https://robohash.org/eosvoluptatibusillum.png?size=100x100&set=set1",
    hex_color: "#e5d719",
    money: "$72.05",
    mobile: "Android 9.0",
  },
  {
    color: "Maroon",
    name: "Karoline Mc Queen",
    image: "https://robohash.org/minimamaximedolorum.png?size=100x100&set=set1",
    hex_color: "#0a3f9d",
    money: "$628.16",
    mobile: "Android 7.0",
  },
  {
    color: "Blue",
    name: "Odetta Fer",
    image:
      "https://robohash.org/nontemporibussuscipit.png?size=100x100&set=set1",
    hex_color: "#e1ba36",
    money: "$711.22",
    mobile: "Feature phone",
  },
  {
    color: "Maroon",
    name: "Fleur Harm",
    image: "https://robohash.org/delectusnisinihil.png?size=100x100&set=set1",
    hex_color: "#1e8091",
    money: "$221.88",
    mobile: "Microsoft Windows Mobile 5.0 Smartphone",
  },
  {
    color: "Mauv",
    name: "Pearce Sate",
    image:
      "https://robohash.org/deseruntquasrepellendus.png?size=100x100&set=set1",
    hex_color: "#d690c1",
    money: "$331.88",
    mobile: "Android 10, EMUI 10, no Google Play Services",
  },
  {
    color: "Yellow",
    name: "Brooke Halse",
    image: "https://robohash.org/enimducimusdeserunt.png?size=100x100&set=set1",
    hex_color: "#670362",
    money: "$16.88",
    mobile: "Feature phone",
  },
  {
    color: "Indigo",
    name: "Palmer Simonnin",
    image: "https://robohash.org/undequodqui.png?size=100x100&set=set1",
    hex_color: "#bc62b2",
    money: "$208.17",
    mobile: "Android 5.0",
  },
  {
    color: "Fuscia",
    name: "Harland Errichiello",
    image: "https://robohash.org/exeaest.png?size=100x100&set=set1",
    hex_color: "#57d46d",
    money: "$548.24",
    mobile: "Feature phone",
  },
  {
    color: "Purple",
    name: "Bryanty Wildin",
    image: "https://robohash.org/maximeseddolores.png?size=100x100&set=set1",
    hex_color: "#0fce41",
    money: "$225.28",
    mobile: "Symbian 9.3, Series 60 rel. 3.2",
  },
  {
    color: "Khaki",
    name: "Boyd Iiannoni",
    image: "https://robohash.org/animinonnihil.png?size=100x100&set=set1",
    hex_color: "#b5f769",
    money: "$371.69",
    mobile: "Feature phone",
  },
  {
    color: "Red",
    name: "Willetta Azam",
    image: "https://robohash.org/numquamutmagnam.png?size=100x100&set=set1",
    hex_color: "#f23774",
    money: "$359.12",
    mobile: "Android 2.3.6",
  },
  {
    color: "Mauv",
    name: "Dorise Meriott",
    image:
      "https://robohash.org/itaqueconsequaturdolores.png?size=100x100&set=set1",
    hex_color: "#6649d4",
    money: "$293.98",
    mobile: "Android 10, up to Android 11, Realme UI 2.0",
  },
  {
    color: "Pink",
    name: "Gilda Megainey",
    image: "https://robohash.org/etadolor.png?size=100x100&set=set1",
    hex_color: "#028da3",
    money: "$222.07",
    mobile: "Feature phone",
  },
  {
    color: "Yellow",
    name: "Sela Slopier",
    image:
      "https://robohash.org/laboriosamarchitectodistinctio.png?size=100x100&set=set1",
    hex_color: "#5ec96e",
    money: "$62.82",
    mobile: "Android 2.3, up to 4.0",
  },
  {
    color: "Indigo",
    name: "Joelly Clough",
    image: "https://robohash.org/quiaseddoloremque.png?size=100x100&set=set1",
    hex_color: "#d1a014",
    money: "$148.77",
    mobile: "Android 2.3",
  },
  {
    color: "Yellow",
    name: "Nani Dyde",
    image: "https://robohash.org/eiusalabore.png?size=100x100&set=set1",
    hex_color: "#23a7a1",
    money: "$287.30",
    mobile: "Microsoft Windows Mobile 2003 SE PocketPC",
  },
  {
    color: "Red",
    name: "Faith Folca",
    image: "https://robohash.org/doloremqueearumad.png?size=100x100&set=set1",
    hex_color: "#002e25",
    money: "$789.03",
    mobile: "Feature phone",
  },
  {
    color: "Yellow",
    name: "Osbourne Gain",
    image:
      "https://robohash.org/consequaturquibusdamdolore.png?size=100x100&set=set1",
    hex_color: "#bd6990",
    money: "$405.36",
    mobile: "Feature phone",
  },
  {
    color: "Yellow",
    name: "Gan Milton",
    image:
      "https://robohash.org/aliasnemovoluptatibus.png?size=100x100&set=set1",
    hex_color: "#7259ac",
    money: "$477.39",
    mobile: "Microsoft Windows Mobile 6.1 Professional",
  },
  {
    color: "Red",
    name: "Leonelle Goghin",
    image: "https://robohash.org/eteosanimi.png?size=100x100&set=set1",
    hex_color: "#50ba7d",
    money: "$750.57",
    mobile: "Feature phone",
  },
  {
    color: "Khaki",
    name: "Fleming Hyett",
    image: "https://robohash.org/commodicupiditateet.png?size=100x100&set=set1",
    hex_color: "#40bab7",
    money: "$282.77",
    mobile: "Microsoft Windows Mobile 2003 Poc&hellip;",
  },
  {
    color: "Aquamarine",
    name: "Sancho Decaze",
    image: "https://robohash.org/dignissimosquiased.png?size=100x100&set=set1",
    hex_color: "#4f2b47",
    money: "$19.18",
    mobile: "Android 10, up to Android 11",
  },
  {
    color: "Puce",
    name: "York Witherden",
    image: "https://robohash.org/itaquetemporetotam.png?size=100x100&set=set1",
    hex_color: "#2f50e2",
    money: "$785.07",
    mobile: "Feature phone",
  },
  {
    color: "Green",
    name: "Kasey Rendle",
    image: "https://robohash.org/etsuntcorrupti.png?size=100x100&set=set1",
    hex_color: "#02bbda",
    money: "$856.28",
    mobile: "Android 8.1, EMUI 8.2",
  },
  {
    color: "Aquamarine",
    name: "Marijn Brimble",
    image: "https://robohash.org/voluptatemsintvel.png?size=100x100&set=set1",
    hex_color: "#784288",
    money: "$79.18",
    mobile: "Android 4.0",
  },
  {
    color: "Violet",
    name: "Montgomery Feldberger",
    image: "https://robohash.org/odioeafacilis.png?size=100x100&set=set1",
    hex_color: "#855d02",
    money: "$133.74",
    mobile: "Feature phone",
  },
  {
    color: "Red",
    name: "Craggie Lutwyche",
    image: "https://robohash.org/istefacerererum.png?size=100x100&set=set1",
    hex_color: "#9dc8a5",
    money: "$528.58",
    mobile: "Symbian 9.2, S60 rel. 3.1",
  },
  {
    color: "Yellow",
    name: "Archy Milburn",
    image:
      "https://robohash.org/voluptatibusautemdolorum.png?size=100x100&set=set1",
    hex_color: "#b04c59",
    money: "$228.48",
    mobile: "Android 10",
  },
  {
    color: "Green",
    name: "Brucie Pitkaithly",
    image: "https://robohash.org/autemautab.png?size=100x100&set=set1",
    hex_color: "#8db6d1",
    money: "$373.04",
    mobile: "Feature phone",
  },
  {
    color: "Crimson",
    name: "Thomas Kusick",
    image: "https://robohash.org/eosvoluptaseum.png?size=100x100&set=set1",
    hex_color: "#0b59c1",
    money: "$883.80",
    mobile: "Feature phone",
  },
  {
    color: "Aquamarine",
    name: "Paco Downes",
    image: "https://robohash.org/suntpariatursoluta.png?size=100x100&set=set1",
    hex_color: "#e0bc40",
    money: "$615.07",
    mobile: "Android 6.0",
  },
  {
    color: "Red",
    name: "Douglas Dunhill",
    image: "https://robohash.org/adipiscidolorat.png?size=100x100&set=set1",
    hex_color: "#576d31",
    money: "$865.87",
    mobile: "watchOS 5.0, up to 7.6",
  },
  {
    color: "Yellow",
    name: "Baxy Ryam",
    image:
      "https://robohash.org/facilissapientevoluptas.png?size=100x100&set=set1",
    hex_color: "#59341c",
    money: "$403.07",
    mobile: "Android 11, Funtouch 10.5",
  },
  {
    color: "Red",
    name: "Tammara Marzele",
    image: "https://robohash.org/utrerumfugiat.png?size=100x100&set=set1",
    hex_color: "#cab696",
    money: "$72.88",
    mobile: "Android 4.4.2",
  },
  {
    color: "Blue",
    name: "Katha Woodsford",
    image:
      "https://robohash.org/accusantiumnostrumcupiditate.png?size=100x100&set=set1",
    hex_color: "#1004a2",
    money: "$540.21",
    mobile: "Feature phone",
  },
  {
    color: "Red",
    name: "Chip Ciobotaru",
    image: "https://robohash.org/placeatquoad.png?size=100x100&set=set1",
    hex_color: "#f0b0e4",
    money: "$533.56",
    mobile: "Microsoft Windows Mobile 6.1 Professional",
  },
  {
    color: "Teal",
    name: "Marcela Gallager",
    image: "https://robohash.org/animivoluptasculpa.png?size=100x100&set=set1",
    hex_color: "#dcb45a",
    money: "$475.33",
    mobile: "Android 5.1.1",
  },
  {
    color: "Khaki",
    name: "Renae Murford",
    image:
      "https://robohash.org/quidoloresvoluptatem.png?size=100x100&set=set1",
    hex_color: "#a5a525",
    money: "$127.45",
    mobile: "Android 4.4.2",
  },
  {
    color: "Puce",
    name: "Jeane Vasyutichev",
    image:
      "https://robohash.org/consequatureumassumenda.png?size=100x100&set=set1",
    hex_color: "#c5dcaf",
    money: "$182.95",
    mobile: "Feature phone",
  },
  {
    color: "Puce",
    name: "Osmond Game",
    image: "https://robohash.org/nonautquidem.png?size=100x100&set=set1",
    hex_color: "#8623a9",
    money: "$226.43",
    mobile: "Symbian 7.0, UIQ v2.1 UI",
  },
  {
    color: "Crimson",
    name: "Nelle Donohoe",
    image: "https://robohash.org/cumquequisquamest.png?size=100x100&set=set1",
    hex_color: "#5ee535",
    money: "$289.70",
    mobile: "Android 5.0",
  },
  {
    color: "Teal",
    name: "Bar Keepin",
    image: "https://robohash.org/voluptatenonmaiores.png?size=100x100&set=set1",
    hex_color: "#8dbbf3",
    money: "$482.43",
    mobile: "Android 7.0",
  },
  {
    color: "Red",
    name: "Ebonee Itter",
    image: "https://robohash.org/rerumetqui.png?size=100x100&set=set1",
    hex_color: "#4e1c8a",
    money: "$616.79",
    mobile: "Feature phone",
  },
  {
    color: "Fuscia",
    name: "Bunnie Skittreal",
    image: "https://robohash.org/nihilinciduntdolore.png?size=100x100&set=set1",
    hex_color: "#18f4fb",
    money: "$267.38",
    mobile: "Feature phone",
  },
  {
    color: "Purple",
    name: "Adriano Flicker",
    image: "https://robohash.org/omnisestvoluptas.png?size=100x100&set=set1",
    hex_color: "#72829c",
    money: "$95.57",
    mobile: "Android 2.3",
  },
  {
    color: "Turquoise",
    name: "Normie Wilmott",
    image: "https://robohash.org/eaquevelvitae.png?size=100x100&set=set1",
    hex_color: "#1260c0",
    money: "$794.67",
    mobile: "Symbian, Series 60 v3.2 UI",
  },
  {
    color: "Crimson",
    name: "Fawnia Mattschas",
    image: "https://robohash.org/autiustoneque.png?size=100x100&set=set1",
    hex_color: "#1097ee",
    money: "$388.83",
    mobile: "Android 7.0, up to Android 8.0",
  },
  {
    color: "Violet",
    name: "Cissiee Mapstone",
    image: "https://robohash.org/laboriosamquiet.png?size=100x100&set=set1",
    hex_color: "#271bf2",
    money: "$777.66",
    mobile: "Microsoft Windows Mobile 6.0 Professional",
  },
  {
    color: "Crimson",
    name: "Ariella Atherton",
    image: "https://robohash.org/vitaesuntvoluptatum.png?size=100x100&set=set1",
    hex_color: "#e3fc83",
    money: "$661.36",
    mobile: "Android 1.5",
  },
  {
    color: "Purple",
    name: "Renata Ruoss",
    image: "https://robohash.org/liberoquidemnihil.png?size=100x100&set=set1",
    hex_color: "#07cd28",
    money: "$18.20",
    mobile: "iOS 6, up to iOS 10.3",
  },
  {
    color: "Yellow",
    name: "Janek Bosquet",
    image: "https://robohash.org/utevenietlaborum.png?size=100x100&set=set1",
    hex_color: "#45ae75",
    money: "$964.89",
    mobile: "Feature phone",
  },
  {
    color: "Teal",
    name: "Dodie Tillman",
    image: "https://robohash.org/nisioditet.png?size=100x100&set=set1",
    hex_color: "#dea729",
    money: "$737.29",
    mobile: "Feature phone",
  },
  {
    color: "Crimson",
    name: "Waldon Filip",
    image:
      "https://robohash.org/utvoluptatemasperiores.png?size=100x100&set=set1",
    hex_color: "#f2ae9c",
    money: "$803.67",
    mobile: "Feature phone",
  },
  {
    color: "Maroon",
    name: "Olenka Uridge",
    image: "https://robohash.org/debitisnobisqui.png?size=100x100&set=set1",
    hex_color: "#8a0f6d",
    money: "$197.65",
    mobile: "Feature phone",
  },
  {
    color: "Turquoise",
    name: "Linnea Teacy",
    image: "https://robohash.org/quiainmagnam.png?size=100x100&set=set1",
    hex_color: "#bdf1be",
    money: "$650.81",
    mobile: "Android 5.1, nubia UI 3",
  },
  {
    color: "Goldenrod",
    name: "Finn Tenny",
    image:
      "https://robohash.org/laborumtemporibusnon.png?size=100x100&set=set1",
    hex_color: "#475849",
    money: "$385.64",
    mobile: "Android 7.0",
  },
  {
    color: "Crimson",
    name: "Jerry Guild",
    image:
      "https://robohash.org/adnecessitatibussapiente.png?size=100x100&set=set1",
    hex_color: "#9e7efe",
    money: "$601.48",
    mobile: "Android 4.2.2",
  },
  {
    color: "Purple",
    name: "Annis Southgate",
    image: "https://robohash.org/enimveniamexcepturi.png?size=100x100&set=set1",
    hex_color: "#62b637",
    money: "$31.44",
    mobile: "Feature phone",
  },
  {
    color: "Pink",
    name: "Woodie Arniz",
    image: "https://robohash.org/errorquisquia.png?size=100x100&set=set1",
    hex_color: "#f421dd",
    money: "$460.85",
    mobile: "Android 6.0",
  },
  {
    color: "Mauv",
    name: "Teador Fabbro",
    image: "https://robohash.org/eamagniducimus.png?size=100x100&set=set1",
    hex_color: "#c81d08",
    money: "$700.00",
    mobile: "Android 5.0, up to 6.0",
  },
  {
    color: "Maroon",
    name: "Timmy Burdikin",
    image: "https://robohash.org/etaperiameaque.png?size=100x100&set=set1",
    hex_color: "#d96a63",
    money: "$118.22",
    mobile: "Feature phone",
  },
  {
    color: "Khaki",
    name: "Tricia Walder",
    image: "https://robohash.org/idreiciendiset.png?size=100x100&set=set1",
    hex_color: "#6fbe12",
    money: "$646.60",
    mobile: "Feature phone",
  },
  {
    color: "Orange",
    name: "Piper Petri",
    image: "https://robohash.org/nobiseligendiqui.png?size=100x100&set=set1",
    hex_color: "#808ed2",
    money: "$695.12",
    mobile: "Feature phone",
  },
  {
    color: "Fuscia",
    name: "Giraud Tull",
    image:
      "https://robohash.org/evenietvoluptatemquo.png?size=100x100&set=set1",
    hex_color: "#e3ec7d",
    money: "$696.36",
    mobile: "Android 4.4.2",
  },
  {
    color: "Orange",
    name: "Aldwin Strother",
    image: "https://robohash.org/omnisessequia.png?size=100x100&set=set1",
    hex_color: "#b3d912",
    money: "$165.74",
    mobile: "Android 4.1",
  },
  {
    color: "Green",
    name: "Erasmus Tire",
    image:
      "https://robohash.org/nihilinventorevoluptatibus.png?size=100x100&set=set1",
    hex_color: "#699666",
    money: "$179.71",
    mobile: "Android 9.0, up to Android 10, MIUI 12",
  },
  {
    color: "Turquoise",
    name: "Malanie Griggs",
    image: "https://robohash.org/consecteturdictaea.png?size=100x100&set=set1",
    hex_color: "#4400be",
    money: "$586.59",
    mobile: "Feature phone",
  },
  {
    color: "Mauv",
    name: "Richmound Cashin",
    image: "https://robohash.org/ullamnatusnon.png?size=100x100&set=set1",
    hex_color: "#4eb15a",
    money: "$345.51",
    mobile: "Android 4.2",
  },
  {
    color: "Orange",
    name: "Happy Doumenc",
    image: "https://robohash.org/veleaqueasperiores.png?size=100x100&set=set1",
    hex_color: "#ae7e26",
    money: "$329.08",
    mobile: "Feature phone",
  },
  {
    color: "Turquoise",
    name: "Collie Coupman",
    image: "https://robohash.org/repellendusatnihil.png?size=100x100&set=set1",
    hex_color: "#d0f35c",
    money: "$428.47",
    mobile: "Android 7.0, up to Android 8.0, EMUI 8",
  },
  {
    color: "Blue",
    name: "Evey Dewitt",
    image:
      "https://robohash.org/esseconsecteturoccaecati.png?size=100x100&set=set1",
    hex_color: "#393b56",
    money: "$330.17",
    mobile: "Android 6.0",
  },
  {
    color: "Teal",
    name: "Danette Dutnell",
    image:
      "https://robohash.org/fugiattemporavoluptates.png?size=100x100&set=set1",
    hex_color: "#0226ed",
    money: "$730.59",
    mobile: "Feature phone",
  },
  {
    color: "Yellow",
    name: "Diarmid Zima",
    image: "https://robohash.org/voluptatemnemovelit.png?size=100x100&set=set1",
    hex_color: "#3d7022",
    money: "$808.85",
    mobile: "Android 9.0, up to Android 10, MIUI 12",
  },
  {
    color: "Puce",
    name: "Bessy Sanchez",
    image: "https://robohash.org/quiautenim.png?size=100x100&set=set1",
    hex_color: "#55d1c7",
    money: "$681.27",
    mobile: "Feature phone",
  },
  {
    color: "Goldenrod",
    name: "Thorpe Zukierman",
    image:
      "https://robohash.org/maioresconsequaturut.png?size=100x100&set=set1",
    hex_color: "#e09787",
    money: "$902.03",
    mobile: "Android 2.1, up to 2.2",
  },
  {
    color: "Mauv",
    name: "Ode Dibdale",
    image: "https://robohash.org/veleavoluptas.png?size=100x100&set=set1",
    hex_color: "#01b911",
    money: "$349.91",
    mobile: "Android 2.3",
  },
  {
    color: "Aquamarine",
    name: "Helen Colebeck",
    image: "https://robohash.org/totamdolorequia.png?size=100x100&set=set1",
    hex_color: "#1ce284",
    money: "$932.29",
    mobile: "Android 2.3, up to 4.0",
  },
  {
    color: "Violet",
    name: "Tobiah Trodd",
    image:
      "https://robohash.org/omnisoccaecatiassumenda.png?size=100x100&set=set1",
    hex_color: "#9b0168",
    money: "$896.79",
    mobile: "Android 4.2.1",
  },
  {
    color: "Purple",
    name: "Guinna Quarlis",
    image:
      "https://robohash.org/molestiasconsequaturincidunt.png?size=100x100&set=set1",
    hex_color: "#d898f8",
    money: "$689.80",
    mobile: "Feature phone",
  },
  {
    color: "Khaki",
    name: "Madalena Tilby",
    image: "https://robohash.org/quisaspernaturneque.png?size=100x100&set=set1",
    hex_color: "#17666a",
    money: "$552.60",
    mobile: "Android 4.2, up to 5.1",
  },
  {
    color: "Purple",
    name: "Judd Cleary",
    image: "https://robohash.org/culpaquibusdamalias.png?size=100x100&set=set1",
    hex_color: "#28d3c3",
    money: "$554.59",
    mobile: "Android 4.1.2, up to 5.1.1",
  },
  {
    color: "Turquoise",
    name: "Clerissa Bahl",
    image: "https://robohash.org/nihiluterror.png?size=100x100&set=set1",
    hex_color: "#fc797f",
    money: "$861.65",
    mobile: "Android 6.0.1",
  },
  {
    color: "Pink",
    name: "Waring Clee",
    image: "https://robohash.org/illumvelmagnam.png?size=100x100&set=set1",
    hex_color: "#1a8b3e",
    money: "$280.29",
    mobile: "Android 8.1, Funtouch 4.5",
  },
  {
    color: "Purple",
    name: "Corty Ferrieres",
    image:
      "https://robohash.org/adipiscimagnamcorporis.png?size=100x100&set=set1",
    hex_color: "#5b5f4e",
    money: "$391.53",
    mobile: "Feature phone",
  },
  {
    color: "Goldenrod",
    name: "Ricki Vairow",
    image: "https://robohash.org/enimetvel.png?size=100x100&set=set1",
    hex_color: "#b6050b",
    money: "$33.20",
    mobile: "Android 4.4.4, Flyme 4",
  },
  {
    color: "Khaki",
    name: "Fannie Camelli",
    image: "https://robohash.org/omnisetquod.png?size=100x100&set=set1",
    hex_color: "#a80abe",
    money: "$409.97",
    mobile: "Android 10, EMUI 10.1",
  },
  {
    color: "Orange",
    name: "Enos Crossfield",
    image: "https://robohash.org/eossedtenetur.png?size=100x100&set=set1",
    hex_color: "#d4885b",
    money: "$594.83",
    mobile: "Android 4.4",
  },
  {
    color: "Teal",
    name: "Zsa zsa Henner",
    image: "https://robohash.org/atidfacere.png?size=100x100&set=set1",
    hex_color: "#8d0751",
    money: "$433.97",
    mobile: "Android 4.2, up to 4.4",
  },
  {
    color: "Indigo",
    name: "Chere Yukhov",
    image: "https://robohash.org/delenitiminimaquasi.png?size=100x100&set=set1",
    hex_color: "#44a936",
    money: "$624.16",
    mobile: "Feature phone",
  },
  {
    color: "Pink",
    name: "Shawn Twallin",
    image:
      "https://robohash.org/exercitationemsequisunt.png?size=100x100&set=set1",
    hex_color: "#fa88b2",
    money: "$198.58",
    mobile: "Feature phone",
  },
  {
    color: "Indigo",
    name: "Fields Dotson",
    image: "https://robohash.org/fugiateanihil.png?size=100x100&set=set1",
    hex_color: "#d04cfb",
    money: "$389.18",
    mobile: "Feature phone",
  },
  {
    color: "Goldenrod",
    name: "Taylor Dobbins",
    image:
      "https://robohash.org/quibusdamlaborummagni.png?size=100x100&set=set1",
    hex_color: "#989add",
    money: "$822.32",
    mobile: "Android 6.0, up to 7.0, EMUI 4.1",
  },
  {
    color: "Mauv",
    name: "Maximo Kefford",
    image:
      "https://robohash.org/etperferendiscupiditate.png?size=100x100&set=set1",
    hex_color: "#e71879",
    money: "$389.28",
    mobile: "Feature phone",
  },
  {
    color: "Maroon",
    name: "Ara Rigby",
    image: "https://robohash.org/nullavelitet.png?size=100x100&set=set1",
    hex_color: "#74343d",
    money: "$730.92",
    mobile: "Android 4.3",
  },
  {
    color: "Crimson",
    name: "Lorena Bittleson",
    image: "https://robohash.org/quosetsed.png?size=100x100&set=set1",
    hex_color: "#c055af",
    money: "$481.88",
    mobile: "Symbian 7.0s, Series 90 UI",
  },
  {
    color: "Green",
    name: "Katerina Lyvon",
    image: "https://robohash.org/eaetmaiores.png?size=100x100&set=set1",
    hex_color: "#53ea68",
    money: "$16.38",
    mobile: "Android 2.3.6",
  },
  {
    color: "Aquamarine",
    name: "Sumner Howlin",
    image: "https://robohash.org/inciduntquidolorum.png?size=100x100&set=set1",
    hex_color: "#bd6357",
    money: "$421.13",
    mobile: "Android 8.1, HIOS 4.1",
  },
  {
    color: "Goldenrod",
    name: "Rufe Bellam",
    image:
      "https://robohash.org/consequaturasperioresea.png?size=100x100&set=set1",
    hex_color: "#5eb74e",
    money: "$611.50",
    mobile: "Android 4.4.2",
  },
  {
    color: "Indigo",
    name: "Dirk Jephcote",
    image: "https://robohash.org/velitipsumex.png?size=100x100&set=set1",
    hex_color: "#b77fcd",
    money: "$190.87",
    mobile: "Feature phone",
  },
  {
    color: "Puce",
    name: "Delcine Siemens",
    image:
      "https://robohash.org/mollitiareiciendisrerum.png?size=100x100&set=set1",
    hex_color: "#d99f9b",
    money: "$776.20",
    mobile: "Android 11, ColorOS 11.1",
  },
  {
    color: "Violet",
    name: "Boigie Corinton",
    image: "https://robohash.org/nemoiustoaut.png?size=100x100&set=set1",
    hex_color: "#6997e3",
    money: "$642.78",
    mobile: "Android 4.2.2",
  },
  {
    color: "Purple",
    name: "Kriste MacParlan",
    image:
      "https://robohash.org/inconsecteturdebitis.png?size=100x100&set=set1",
    hex_color: "#1c134a",
    money: "$588.92",
    mobile: "Android 10, MIUI 12",
  },
  {
    color: "Yellow",
    name: "Emlynn Oguz",
    image: "https://robohash.org/facerepossimuset.png?size=100x100&set=set1",
    hex_color: "#5d871a",
    money: "$125.17",
    mobile: "Feature phone",
  },
  {
    color: "Turquoise",
    name: "Tades Emeney",
    image:
      "https://robohash.org/aliascupiditateharum.png?size=100x100&set=set1",
    hex_color: "#54ca48",
    money: "$709.68",
    mobile: "Android 4.1",
  },
  {
    color: "Blue",
    name: "Mildred Dunkersley",
    image:
      "https://robohash.org/quovoluptatevoluptas.png?size=100x100&set=set1",
    hex_color: "#3f40ae",
    money: "$666.99",
    mobile: "Feature phone",
  },
  {
    color: "Green",
    name: "Petey Plumer",
    image: "https://robohash.org/atqueestquia.png?size=100x100&set=set1",
    hex_color: "#a4701d",
    money: "$293.59",
    mobile: "Android 5.1",
  },
  {
    color: "Violet",
    name: "Caty Keddy",
    image: "https://robohash.org/quasquinihil.png?size=100x100&set=set1",
    hex_color: "#b5a9ce",
    money: "$690.27",
    mobile: "Android 8.1, up to Android 9.0",
  },
  {
    color: "Aquamarine",
    name: "Obidiah Duxfield",
    image: "https://robohash.org/inciduntsitqui.png?size=100x100&set=set1",
    hex_color: "#259324",
    money: "$321.60",
    mobile: "Android 2.3",
  },
  {
    color: "Pink",
    name: "Dian Paulley",
    image:
      "https://robohash.org/reprehenderitrationevoluptates.png?size=100x100&set=set1",
    hex_color: "#ea0fb6",
    money: "$198.43",
    mobile: "Linux / Java-based MOTOMAGX",
  },
  {
    color: "Crimson",
    name: "Pier Eads",
    image: "https://robohash.org/utpossimusest.png?size=100x100&set=set1",
    hex_color: "#4b1dcf",
    money: "$13.94",
    mobile: "Android 4.4.2",
  },
  {
    color: "Red",
    name: "Petey Chessman",
    image: "https://robohash.org/voluptasoptioquod.png?size=100x100&set=set1",
    hex_color: "#bc5ddf",
    money: "$213.96",
    mobile: "Feature phone",
  },
  {
    color: "Violet",
    name: "Woodman Imorts",
    image: "https://robohash.org/eaquohic.png?size=100x100&set=set1",
    hex_color: "#f5ffd0",
    money: "$76.98",
    mobile: "Feature phone",
  },
  {
    color: "Red",
    name: "Corbet Abrahart",
    image: "https://robohash.org/harumdolorut.png?size=100x100&set=set1",
    hex_color: "#95172b",
    money: "$787.33",
    mobile: "Feature phone",
  },
  {
    color: "Mauv",
    name: "Alexander Imrie",
    image: "https://robohash.org/delectusetomnis.png?size=100x100&set=set1",
    hex_color: "#6664d5",
    money: "$435.56",
    mobile: "Feature phone",
  },
  {
    color: "Puce",
    name: "Keeley Alishoner",
    image: "https://robohash.org/saepevoluptatibuset.png?size=100x100&set=set1",
    hex_color: "#56a2c1",
    money: "$576.75",
    mobile: "Feature phone",
  },
  {
    color: "Orange",
    name: "Edvard McKall",
    image: "https://robohash.org/noncumquevoluptatum.png?size=100x100&set=set1",
    hex_color: "#a54f90",
    money: "$479.18",
    mobile: "Android 4.4.4, up to Android L",
  },
  {
    color: "Red",
    name: "Evangeline Normanville",
    image:
      "https://robohash.org/voluptatemquisquamqui.png?size=100x100&set=set1",
    hex_color: "#82b1f2",
    money: "$641.02",
    mobile: "Android 5.1.1, nubia UI 4",
  },
  {
    color: "Teal",
    name: "Jacquelyn Kent",
    image: "https://robohash.org/utperferendisrerum.png?size=100x100&set=set1",
    hex_color: "#567fa2",
    money: "$881.40",
    mobile: "Android 7.0",
  },
  {
    color: "Purple",
    name: "Benetta Revie",
    image:
      "https://robohash.org/voluptasvoluptatemut.png?size=100x100&set=set1",
    hex_color: "#bb069a",
    money: "$326.22",
    mobile: "Feature phone",
  },
  {
    color: "Puce",
    name: "Danita Crowcum",
    image: "https://robohash.org/etquiadolor.png?size=100x100&set=set1",
    hex_color: "#3103d0",
    money: "$705.36",
    mobile: "Android 4.4.2",
  },
  {
    color: "Pink",
    name: "Sorcha Comerford",
    image: "https://robohash.org/molestiaealiquamsit.png?size=100x100&set=set1",
    hex_color: "#35c6ca",
    money: "$587.46",
    mobile: "Feature phone",
  },
  {
    color: "Pink",
    name: "Hoebart Alldre",
    image: "https://robohash.org/expeditaabsequi.png?size=100x100&set=set1",
    hex_color: "#216011",
    money: "$274.15",
    mobile: "Android 2.3.5",
  },
  {
    color: "Aquamarine",
    name: "Una Croster",
    image: "https://robohash.org/officiisadolorem.png?size=100x100&set=set1",
    hex_color: "#67e4c9",
    money: "$630.24",
    mobile: "Android 4.4.2, up to 6.0.1, TouchWiz UI",
  },
  {
    color: "Purple",
    name: "Lucine Yeoman",
    image: "https://robohash.org/animinoninventore.png?size=100x100&set=set1",
    hex_color: "#d8879e",
    money: "$12.87",
    mobile: "Android 4.4.4, up to 6.0",
  },
  {
    color: "Maroon",
    name: "Kirstin Pietzke",
    image: "https://robohash.org/sequicorporisautem.png?size=100x100&set=set1",
    hex_color: "#4e72fa",
    money: "$192.52",
    mobile: "Feature phone",
  },
  {
    color: "Aquamarine",
    name: "Yorker Levington",
    image: "https://robohash.org/quaeautest.png?size=100x100&set=set1",
    hex_color: "#e8c233",
    money: "$848.91",
    mobile: "BlackBerry OS",
  },
  {
    color: "Blue",
    name: "Amelita Muge",
    image: "https://robohash.org/quispossimusaliquam.png?size=100x100&set=set1",
    hex_color: "#6d44e1",
    money: "$76.59",
    mobile: "Android 7, Amigo 4",
  },
  {
    color: "Violet",
    name: "Cari Bottleson",
    image:
      "https://robohash.org/etdignissimospariatur.png?size=100x100&set=set1",
    hex_color: "#796be9",
    money: "$428.48",
    mobile: "Android 2.3.4",
  },
  {
    color: "Maroon",
    name: "Rosalynd Rubee",
    image:
      "https://robohash.org/velaccusamusmollitia.png?size=100x100&set=set1",
    hex_color: "#3e98c2",
    money: "$884.37",
    mobile: "Android 2.2",
  },
  {
    color: "Purple",
    name: "Thornie Letcher",
    image: "https://robohash.org/etutdignissimos.png?size=100x100&set=set1",
    hex_color: "#087231",
    money: "$610.66",
    mobile: "Feature phone",
  },
  {
    color: "Puce",
    name: "Rudy Berfoot",
    image:
      "https://robohash.org/nostrumporroperspiciatis.png?size=100x100&set=set1",
    hex_color: "#ce7721",
    money: "$147.12",
    mobile: "Feature phone",
  },
  {
    color: "Yellow",
    name: "Webster Ranald",
    image:
      "https://robohash.org/molestiasrerumvoluptas.png?size=100x100&set=set1",
    hex_color: "#4c3a70",
    money: "$601.43",
    mobile: "Android 10, Funtouch 10.5",
  },
  {
    color: "Aquamarine",
    name: "Harrietta Varndell",
    image:
      "https://robohash.org/errorveritatisnesciunt.png?size=100x100&set=set1",
    hex_color: "#9b548c",
    money: "$810.88",
    mobile: "Feature phone",
  },
  {
    color: "Blue",
    name: "Alika Stansell",
    image:
      "https://robohash.org/voluptatemdolorequia.png?size=100x100&set=set1",
    hex_color: "#d544c7",
    money: "$524.41",
    mobile: "Android 5.1",
  },
  {
    color: "Red",
    name: "Alta Radborne",
    image: "https://robohash.org/excepturiducimussit.png?size=100x100&set=set1",
    hex_color: "#540abf",
    money: "$962.73",
    mobile: "Feature phone",
  },
  {
    color: "Crimson",
    name: "Hollyanne Rigardeau",
    image:
      "https://robohash.org/similiquesaepefugiat.png?size=100x100&set=set1",
    hex_color: "#52eeee",
    money: "$879.62",
    mobile: "Feature phone",
  },
  {
    color: "Violet",
    name: "Nance Izachik",
    image: "https://robohash.org/veniamsuscipitest.png?size=100x100&set=set1",
    hex_color: "#98337e",
    money: "$366.30",
    mobile: "Feature phone",
  },
  {
    color: "Teal",
    name: "Meta McSherry",
    image: "https://robohash.org/nostrumevenietvitae.png?size=100x100&set=set1",
    hex_color: "#7fc872",
    money: "$921.11",
    mobile: "Feature phone",
  },
  {
    color: "Aquamarine",
    name: "Perri Marmon",
    image: "https://robohash.org/sedillumsunt.png?size=100x100&set=set1",
    hex_color: "#f4b8d8",
    money: "$925.68",
    mobile: "Android 6.0, up to Android 8.0",
  },
  {
    color: "Maroon",
    name: "Lanette Kachel",
    image: "https://robohash.org/estsequidolore.png?size=100x100&set=set1",
    hex_color: "#c72f8e",
    money: "$273.56",
    mobile: "Feature phone",
  },
  {
    color: "Puce",
    name: "Saunderson Breawood",
    image:
      "https://robohash.org/accusamuspossimusqui.png?size=100x100&set=set1",
    hex_color: "#aae2dd",
    money: "$411.40",
    mobile: "Feature phone",
  },
  {
    color: "Purple",
    name: "Riobard Dupre",
    image: "https://robohash.org/perspiciatisutomnis.png?size=100x100&set=set1",
    hex_color: "#5fb05d",
    money: "$776.68",
    mobile: "Symbian^3, up to Nokia Belle OS",
  },
  {
    color: "Aquamarine",
    name: "Scarface Fidgett",
    image: "https://robohash.org/quaedoloremmagnam.png?size=100x100&set=set1",
    hex_color: "#fa07a9",
    money: "$983.36",
    mobile: "Android 4.1.2",
  },
  {
    color: "Teal",
    name: "Nert Selman",
    image:
      "https://robohash.org/asperioresmolestiaeexpedita.png?size=100x100&set=set1",
    hex_color: "#86a8d3",
    money: "$485.11",
    mobile: "Android 6.0",
  },
  {
    color: "Khaki",
    name: "Wernher Maxsted",
    image: "https://robohash.org/molestiaeetnon.png?size=100x100&set=set1",
    hex_color: "#5ea451",
    money: "$669.11",
    mobile: "Android 6.0",
  },
  {
    color: "Indigo",
    name: "Madalyn Denton",
    image: "https://robohash.org/enimdignissimosvero.png?size=100x100&set=set1",
    hex_color: "#3482dc",
    money: "$889.91",
    mobile: "Feature phone",
  },
  {
    color: "Khaki",
    name: "Ally Marchello",
    image: "https://robohash.org/nonofficiisquod.png?size=100x100&set=set1",
    hex_color: "#93bcfb",
    money: "$530.20",
    mobile: "Feature phone",
  },
  {
    color: "Red",
    name: "Darlleen Storkes",
    image:
      "https://robohash.org/laudantiumdistinctiotenetur.png?size=100x100&set=set1",
    hex_color: "#df282f",
    money: "$871.05",
    mobile: "Feature phone",
  },
  {
    color: "Red",
    name: "Gayelord Deetlefs",
    image: "https://robohash.org/ipsumhicid.png?size=100x100&set=set1",
    hex_color: "#4d1f61",
    money: "$82.58",
    mobile: "Android 2.2, up to 2.3",
  },
  {
    color: "Indigo",
    name: "Haskel Ghio",
    image: "https://robohash.org/iureeumsint.png?size=100x100&set=set1",
    hex_color: "#b29cad",
    money: "$733.68",
    mobile: "Android 2.3",
  },
  {
    color: "Puce",
    name: "Jolie Bouchier",
    image: "https://robohash.org/quoderroret.png?size=100x100&set=set1",
    hex_color: "#324534",
    money: "$368.74",
    mobile: "Feature phone",
  },
  {
    color: "Mauv",
    name: "Karney Purvis",
    image: "https://robohash.org/maximeutminima.png?size=100x100&set=set1",
    hex_color: "#0eb393",
    money: "$341.81",
    mobile: "Microsoft Smartphone 2003 SE OS",
  },
  {
    color: "Pink",
    name: "Paola Forsdyke",
    image: "https://robohash.org/mollitiafugatempore.png?size=100x100&set=set1",
    hex_color: "#dc8f52",
    money: "$464.24",
    mobile: "Feature phone",
  },
  {
    color: "Fuscia",
    name: "Ophelia McAllan",
    image: "https://robohash.org/eoscupiditatedicta.png?size=100x100&set=set1",
    hex_color: "#2fa0a7",
    money: "$356.45",
    mobile: "Android 4.4.2",
  },
  {
    color: "Mauv",
    name: "Else Sharply",
    image: "https://robohash.org/commodinonmaiores.png?size=100x100&set=set1",
    hex_color: "#5ce034",
    money: "$281.79",
    mobile: "Feature phone",
  },
  {
    color: "Aquamarine",
    name: "Remus Thing",
    image: "https://robohash.org/eligendiofficiavero.png?size=100x100&set=set1",
    hex_color: "#1afb1a",
    money: "$262.66",
    mobile: "Microsoft Windows Mobile 6.5 Professional",
  },
  {
    color: "Pink",
    name: "Codi Stockoe",
    image: "https://robohash.org/auteminvoluptatem.png?size=100x100&set=set1",
    hex_color: "#d01868",
    money: "$787.07",
    mobile: "BlackBerry OS 10.2.1, up to 10.3.1",
  },
  {
    color: "Maroon",
    name: "Oriana Citrine",
    image: "https://robohash.org/eteadicta.png?size=100x100&set=set1",
    hex_color: "#7bfca8",
    money: "$420.27",
    mobile: "Proprietary OS",
  },
  {
    color: "Maroon",
    name: "Kerk Rivaland",
    image:
      "https://robohash.org/quiaexplicaboinventore.png?size=100x100&set=set1",
    hex_color: "#fac9d4",
    money: "$892.88",
    mobile: "Android 2.2, TouchWiz UI 3",
  },
  {
    color: "Aquamarine",
    name: "Susann Broggini",
    image: "https://robohash.org/nostrumpossimussed.png?size=100x100&set=set1",
    hex_color: "#eb8bc6",
    money: "$716.16",
    mobile: "Feature phone",
  },
  {
    color: "Pink",
    name: "Dori Statersfield",
    image:
      "https://robohash.org/corporismolestiaequia.png?size=100x100&set=set1",
    hex_color: "#ee7910",
    money: "$941.48",
    mobile: "Feature phone",
  },
  {
    color: "Aquamarine",
    name: "Brier Yardley",
    image: "https://robohash.org/saepecumquequi.png?size=100x100&set=set1",
    hex_color: "#b8d7e6",
    money: "$462.83",
    mobile: "Feature phone",
  },
  {
    color: "Khaki",
    name: "Jeannine Varley",
    image: "https://robohash.org/consecteturatest.png?size=100x100&set=set1",
    hex_color: "#b376e2",
    money: "$933.89",
    mobile: "Android 4.4",
  },
  {
    color: "Puce",
    name: "Fanya Whitehair",
    image:
      "https://robohash.org/doloribusadipiscieligendi.png?size=100x100&set=set1",
    hex_color: "#29d01a",
    money: "$377.13",
    mobile: "Feature phone",
  },
  {
    color: "Maroon",
    name: "Harwilll Casley",
    image:
      "https://robohash.org/fugiatadipiscicommodi.png?size=100x100&set=set1",
    hex_color: "#64c48a",
    money: "$661.76",
    mobile: "Microsoft Windows Mobile 5.0 Smartphone",
  },
  {
    color: "Teal",
    name: "Payton Mushett",
    image:
      "https://robohash.org/saepequibusdamitaque.png?size=100x100&set=set1",
    hex_color: "#e76ec2",
    money: "$940.76",
    mobile: "Microsoft Windows CE.NET",
  },
  {
    color: "Teal",
    name: "Burtie Heaffey",
    image: "https://robohash.org/sedevenietsuscipit.png?size=100x100&set=set1",
    hex_color: "#3380f5",
    money: "$854.35",
    mobile: "Microsoft Windows 10",
  },
  {
    color: "Purple",
    name: "Aluin Wingham",
    image:
      "https://robohash.org/laboreadipisciquisquam.png?size=100x100&set=set1",
    hex_color: "#4273b0",
    money: "$853.84",
    mobile: "Android 9.0, up to Android 10, Redmagic 3.0",
  },
  {
    color: "Maroon",
    name: "Lowrance Dobbings",
    image: "https://robohash.org/minimatemporaeum.png?size=100x100&set=set1",
    hex_color: "#3b1608",
    money: "$485.61",
    mobile: "iOS 10.3.2, up to iPadOS 14.6",
  },
  {
    color: "Pink",
    name: "Eadie MacGiolla Pheadair",
    image: "https://robohash.org/sinteasaepe.png?size=100x100&set=set1",
    hex_color: "#419888",
    money: "$963.89",
    mobile: "Android 10",
  },
  {
    color: "Green",
    name: "Abby Guillet",
    image: "https://robohash.org/voluptatemettotam.png?size=100x100&set=set1",
    hex_color: "#3ef578",
    money: "$579.14",
    mobile: "Feature phone",
  },
  {
    color: "Red",
    name: "Eve Wann",
    image: "https://robohash.org/iustoeligendisint.png?size=100x100&set=set1",
    hex_color: "#955333",
    money: "$576.98",
    mobile: "Android 2.3, up to 4.0.4",
  },
  {
    color: "Blue",
    name: "Maddy Leadstone",
    image: "https://robohash.org/veleumdolores.png?size=100x100&set=set1",
    hex_color: "#0eed28",
    money: "$375.49",
    mobile: "Feature phone",
  },
  {
    color: "Aquamarine",
    name: "Deanna Gurg",
    image: "https://robohash.org/nullaeosillo.png?size=100x100&set=set1",
    hex_color: "#26cf51",
    money: "$80.60",
    mobile: "Feature phone",
  },
  {
    color: "Khaki",
    name: "Adella Lorenzin",
    image: "https://robohash.org/totameumreiciendis.png?size=100x100&set=set1",
    hex_color: "#830c37",
    money: "$730.37",
    mobile: "bada OS",
  },
  {
    color: "Orange",
    name: "Kenton Frances",
    image: "https://robohash.org/iuresolutavoluptate.png?size=100x100&set=set1",
    hex_color: "#514307",
    money: "$854.44",
    mobile: "Android 4.2.2, up to 4.4.2",
  },
  {
    color: "Fuscia",
    name: "Gregory Kondratyuk",
    image: "https://robohash.org/nequemagninihil.png?size=100x100&set=set1",
    hex_color: "#efc71a",
    money: "$849.16",
    mobile: "Feature phone",
  },
  {
    color: "Aquamarine",
    name: "Neils Devenny",
    image: "https://robohash.org/illumquiquibusdam.png?size=100x100&set=set1",
    hex_color: "#2f2b79",
    money: "$778.91",
    mobile: "Android 8.1, up to Android 10, EMUI 10.0",
  },
  {
    color: "Maroon",
    name: "Dorthea Shepard",
    image:
      "https://robohash.org/dictaarchitectonecessitatibus.png?size=100x100&set=set1",
    hex_color: "#b49f95",
    money: "$564.20",
    mobile: "Feature phone",
  },
  {
    color: "Orange",
    name: "Teressa Eastcott",
    image: "https://robohash.org/nihildolorumsit.png?size=100x100&set=set1",
    hex_color: "#490b70",
    money: "$925.88",
    mobile: "Android 9.0, up to Android 11, One UI 3.1",
  },
];
