export const ablyData = [
  {
    type: "GOODS_CARD",
    item_entity: {
      item: {
        sno: 17663829,
        name: "정품보장💗스파오 SPAO 보들보들 후리스 집업 10컬러",
        market_sno: 64739,
        market_name: "제이와이홀딩스",
        image:
          "https://d3ha2047wt6x28.cloudfront.net/038iy9jUgMA/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzU1MWFmYjQyN2I5MzgyZjZlMzc0NWE1YjliMzQzYjdiLmdpZg",
        closed_reason: null,
        sell_count: 13765,
        delivery_type: "standard",
        ranking: null,
        available_only_new_member: false,
        first_page_rendering: {
          goods_name: "정품보장💗스파오 SPAO 보들보들 후리스 집업 10컬러",
          market_name: null,
          cover_image:
            "https://d3ha2047wt6x28.cloudfront.net/OlvDMHrqRzo/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDE4XzE3MjkyNDgwNjk0NTYyOTltLnBuZw",
          market_image: null,
          discount_rate: 3,
          original_price: 29900,
          price: 28800,
        },
        is_premium_hotdeal: false,
        is_hotdeal: false,
        is_new: false,
        price: 28800,
        discount_rate: 3,
        like: {
          goods_sno: 17663829,
          is_liked: false,
          folder_sno: null,
          referrer: {
            list_id: "today_recommend",
            list_index: 3,
          },
        },
        ad: null,
        on_return: {
          type: "INJECT",
          data: {
            url: "goods/17663829/recommend_related_goods_by_click_for_today/?from=TODAY",
          },
        },
        market_type: "프리미엄 브랜드",
        category_name: "플리스",
        feedback_type: "contain_icon",
        remote_deeplink:
          "ably://goods/17663829/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5Cuc815%5Cud488%5Cubcf4%5Cuc7a5%5Cud83d%5Cudc97%5Cuc2a4%5Cud30c%5Cuc624%20SPAO%20%5Cubcf4%5Cub4e4%5Cubcf4%5Cub4e4%20%5Cud6c4%5Cub9ac%5Cuc2a4%20%5Cuc9d1%5Cuc5c5%2010%5Cuceec%5Cub7ec%22%2C%20%22market_name%22%3A%20null%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FOlvDMHrqRzo%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDE4XzE3MjkyNDgwNjk0NTYyOTltLnBuZw%22%2C%20%22market_image%22%3A%20null%2C%20%22discount_rate%22%3A%203%2C%20%22original_price%22%3A%2029900%2C%20%22price%22%3A%2028800%7D",
      },
      logging: {
        analytics: {
          GOODS_SNO: "17663829",
          GOODS_NAME: "정품보장💗스파오 SPAO 보들보들 후리스 집업 10컬러",
          MARKET_TYPE: "프리미엄 브랜드",
          MARKET_SNO: "64739",
          MARKET_NAME: "제이와이홀딩스",
          CATEGORY_SNO: "577",
          CATEGORY_NAME: "플리스",
          STANDARD_CATEGORY_SNO: "12",
          STANDARD_CATEGORY_NAME: "플리스",
          DISCOUNT_RATE: 3,
          SALES_PRICE: 28800,
          SALES_PRICE_RANGE: "25,001~30,000",
          IS_NEW: "0",
          DELIVERY_TYPE: "standard",
          IS_AD: "0",
          LIST_PARAMS: null,
          MARKET_TYPE_SNO: "16",
          REVIEW_COUNT: 897,
          REVIEW_COUNT_RANGE: "851~900",
          REVIEW_RATING: 97,
          LIKES_COUNT: 26194,
          LIKES_COUNT_RANGE: "26,151~26,200",
          DELIVERY_SCORE: null,
          PROMOTION_TAG: ["BRAND"],
          UPCOMMING_SOLDOUT: "",
          HAS_AWARD: false,
          IS_ONLY_ABLY: false,
          LIST_ID: "today_recommend",
          LIST_INDEX: 3,
          BRAND_SNO: 15609,
          BRAND_NAME: "스파오",
          CARD_TYPE: "GOODS_CARD",
        },
        inhouse: {
          goods_sno: 17663829,
          list_id: "today_recommend",
          list_index: 3,
          schema_name: "Goods",
          pool: "best",
        },
      },
      render: {
        type: "MARKET_NUDGING_CHIPS",
        contents: ["PRICE", "NAME", "MARKET", "NUDGING", "CHIPS"],
        size: "MEDIUM",
        data: {
          image: {
            url: "https://d3ha2047wt6x28.cloudfront.net/038iy9jUgMA/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzU1MWFmYjQyN2I5MzgyZjZlMzc0NWE1YjliMzQzYjdiLmdpZg",
            use_animation: true,
            ratio: 1.2,
          },
          name: "정품보장💗스파오 SPAO 보들보들 후리스 집업 10컬러",
          price: "28,800",
          has_ad_badge: false,
          name_lines: 1,
          discount_rate: "3%",
          closed_reason: null,
          image_badge: null,
          image_badge_width: null,
          image_badge_height: null,
          chips: [
            {
              type: "BRAND",
              name: "브랜드",
            },
          ],
          market_name: "스파오",
          store_text: "<font color='#6093FC'>브랜드</font> 스파오",
          nudging_text: "13,765개 구매중",
          ranking: null,
          actions: ["LIKE"],
          discount_end_text: null,
          top_nudging_text: null,
          price_description: null,
          today_delivery_order_deadline_time: null,
        },
      },
    },
  },
  {
    type: "GOODS_CARD",
    item_entity: {
      item: {
        sno: 32396742,
        name: "[왕도톰! 무조건만족! /기모안감] 융골덴 기모 스트링 와이드 팬츠 5color",
        market_sno: 1211,
        market_name: "럽앤썸",
        image:
          "https://d3ha2047wt6x28.cloudfront.net/_XdRKUZocvs/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzFhYTljYmM3ZTU2YzEzZjMyYTE0MTdhNWNlNjcyYTYxLmdpZg",
        closed_reason: null,
        sell_count: 2085,
        delivery_type: "standard",
        ranking: null,
        available_only_new_member: false,
        first_page_rendering: {
          goods_name:
            "[왕도톰! 무조건만족! /기모안감] 융골덴 기모 스트링 와이드 팬츠 5color",
          market_name: "럽앤썸",
          cover_image:
            "https://d3ha2047wt6x28.cloudfront.net/UdAc6Iam1DU/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDMwXzE3MzAyOTYzNTAwMTU0NjBtLmdpZg",
          market_image:
            "https://d3ha2047wt6x28.cloudfront.net/xNX9wdRVPQI/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE2NzE2MDEzNTc5OTM4MDAuanBn",
          discount_rate: 0,
          original_price: 14900,
          price: 14900,
        },
        is_premium_hotdeal: false,
        is_hotdeal: false,
        is_new: false,
        price: 14900,
        discount_rate: 0,
        like: {
          goods_sno: 32396742,
          is_liked: false,
          folder_sno: null,
          referrer: {
            list_id: "today_recommend",
            list_index: 4,
          },
        },
        ad: null,
        on_return: {
          type: "INJECT",
          data: {
            url: "goods/32396742/recommend_related_goods_by_click_for_today/?from=TODAY",
          },
        },
        market_type: "셀럽",
        category_name: "롱팬츠",
        feedback_type: "contain_icon",
        remote_deeplink:
          "ably://goods/32396742/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5B%5Cuc655%5Cub3c4%5Cud1b0%21%20%5Cubb34%5Cuc870%5Cuac74%5Cub9cc%5Cuc871%21%20%2F%5Cuae30%5Cubaa8%5Cuc548%5Cuac10%5D%20%5Cuc735%5Cuace8%5Cub374%20%5Cuae30%5Cubaa8%20%5Cuc2a4%5Cud2b8%5Cub9c1%20%5Cuc640%5Cuc774%5Cub4dc%20%5Cud32c%5Cuce20%205color%22%2C%20%22market_name%22%3A%20%22%5Cub7fd%5Cuc564%5Cuc378%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FUdAc6Iam1DU%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDMwXzE3MzAyOTYzNTAwMTU0NjBtLmdpZg%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FxNX9wdRVPQI%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE2NzE2MDEzNTc5OTM4MDAuanBn%22%2C%20%22discount_rate%22%3A%200%2C%20%22original_price%22%3A%2014900%2C%20%22price%22%3A%2014900%7D",
      },
      logging: {
        analytics: {
          GOODS_SNO: "32396742",
          GOODS_NAME:
            "[왕도톰! 무조건만족! /기모안감] 융골덴 기모 스트링 와이드 팬츠 5color",
          MARKET_TYPE: "셀럽",
          MARKET_SNO: "1211",
          MARKET_NAME: "럽앤썸",
          CATEGORY_SNO: "176",
          CATEGORY_NAME: "롱팬츠",
          STANDARD_CATEGORY_SNO: "73",
          STANDARD_CATEGORY_NAME: "롱팬츠",
          DISCOUNT_RATE: 0,
          SALES_PRICE: 14900,
          SALES_PRICE_RANGE: "10,001~15,000",
          IS_NEW: "0",
          DELIVERY_TYPE: "standard",
          IS_AD: "0",
          LIST_PARAMS: null,
          MARKET_TYPE_SNO: "7",
          REVIEW_COUNT: 9,
          REVIEW_COUNT_RANGE: "1~50",
          REVIEW_RATING: 88,
          LIKES_COUNT: 7356,
          LIKES_COUNT_RANGE: "7,351~7,400",
          DELIVERY_SCORE: null,
          PROMOTION_TAG: [],
          UPCOMMING_SOLDOUT: "",
          HAS_AWARD: false,
          IS_ONLY_ABLY: false,
          LIST_ID: "today_recommend",
          LIST_INDEX: 4,
          CARD_TYPE: "GOODS_CARD",
        },
        inhouse: {
          goods_sno: 32396742,
          list_id: "today_recommend",
          list_index: 4,
          schema_name: "Goods",
          pool: "best",
        },
      },
      render: {
        type: "MARKET_NUDGING",
        contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
        size: "MEDIUM",
        data: {
          image: {
            url: "https://d3ha2047wt6x28.cloudfront.net/_XdRKUZocvs/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzFhYTljYmM3ZTU2YzEzZjMyYTE0MTdhNWNlNjcyYTYxLmdpZg",
            use_animation: true,
            ratio: 1.2,
          },
          name: "[왕도톰! 무조건만족! /기모안감] 융골덴 기모 스트링 와이드 팬츠 5color",
          price: "14,900",
          has_ad_badge: false,
          name_lines: 1,
          discount_rate: null,
          closed_reason: null,
          image_badge: null,
          image_badge_width: null,
          image_badge_height: null,
          chips: null,
          market_name: "럽앤썸",
          store_text: "럽앤썸",
          nudging_text: "2,085개 구매중",
          ranking: null,
          actions: ["LIKE"],
          discount_end_text: null,
          top_nudging_text: null,
          price_description: null,
          today_delivery_order_deadline_time: null,
        },
      },
    },
  },
  {
    type: "GOODS_CARD",
    item_entity: {
      item: {
        sno: 31315514,
        name: "[귀여움/아방핏] 포근 후드 양털 떡볶이 퍼자켓 숏코트 덤블점퍼",
        market_sno: 370,
        market_name: "블리즈",
        image:
          "https://d3ha2047wt6x28.cloudfront.net/-zZT6otp0-g/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2ZmZGZhNTY4ZGU0NDRmZTYwMmMyMjA3NzZmNTNkYzQxLmdpZg",
        closed_reason: null,
        sell_count: 3247,
        delivery_type: "standard",
        ranking: null,
        available_only_new_member: false,
        first_page_rendering: {
          goods_name:
            "[귀여움/아방핏] 포근 후드 양털 떡볶이 퍼자켓 숏코트 덤블점퍼",
          market_name: "블리즈",
          cover_image:
            "https://d3ha2047wt6x28.cloudfront.net/E6FCgfqh6As/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDIxXzE3Mjk0OTEzNDIwMjA5MjNtLmpwZw",
          market_image:
            "https://d3ha2047wt6x28.cloudfront.net/99tr9Fb97to/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjkxODY1MDE1NTM2MTguanBn",
          discount_rate: 15,
          original_price: 51400,
          price: 43700,
        },
        is_premium_hotdeal: false,
        is_hotdeal: false,
        is_new: false,
        price: 43700,
        discount_rate: 15,
        like: {
          goods_sno: 31315514,
          is_liked: false,
          folder_sno: null,
          referrer: {
            list_id: "today_recommend",
            list_index: 5,
          },
        },
        ad: null,
        on_return: {
          type: "INJECT",
          data: {
            url: "goods/31315514/recommend_related_goods_by_click_for_today/?from=TODAY",
          },
        },
        market_type: "셀럽",
        category_name: "코트",
        feedback_type: "contain_icon",
        remote_deeplink:
          "ably://goods/31315514/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5B%5Cuadc0%5Cuc5ec%5Cuc6c0%2F%5Cuc544%5Cubc29%5Cud54f%5D%20%5Cud3ec%5Cuadfc%20%5Cud6c4%5Cub4dc%20%5Cuc591%5Cud138%20%5Cub5a1%5Cubcf6%5Cuc774%20%5Cud37c%5Cuc790%5Cucf13%20%5Cuc20f%5Cucf54%5Cud2b8%20%5Cub364%5Cube14%5Cuc810%5Cud37c%22%2C%20%22market_name%22%3A%20%22%5Cube14%5Cub9ac%5Cuc988%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FE6FCgfqh6As%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDIxXzE3Mjk0OTEzNDIwMjA5MjNtLmpwZw%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2F99tr9Fb97to%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjkxODY1MDE1NTM2MTguanBn%22%2C%20%22discount_rate%22%3A%2015%2C%20%22original_price%22%3A%2051400%2C%20%22price%22%3A%2043700%7D",
      },
      logging: {
        analytics: {
          GOODS_SNO: "31315514",
          GOODS_NAME:
            "[귀여움/아방핏] 포근 후드 양털 떡볶이 퍼자켓 숏코트 덤블점퍼",
          MARKET_TYPE: "셀럽",
          MARKET_SNO: "370",
          MARKET_NAME: "블리즈",
          CATEGORY_SNO: "296",
          CATEGORY_NAME: "코트",
          STANDARD_CATEGORY_SNO: "8",
          STANDARD_CATEGORY_NAME: "코트",
          DISCOUNT_RATE: 15,
          SALES_PRICE: 43700,
          SALES_PRICE_RANGE: "40,001~45,000",
          IS_NEW: "0",
          DELIVERY_TYPE: "standard",
          IS_AD: "0",
          LIST_PARAMS: null,
          MARKET_TYPE_SNO: "7",
          REVIEW_COUNT: 12,
          REVIEW_COUNT_RANGE: "1~50",
          REVIEW_RATING: 91,
          LIKES_COUNT: 20804,
          LIKES_COUNT_RANGE: "20,801~20,850",
          DELIVERY_SCORE: null,
          PROMOTION_TAG: [],
          UPCOMMING_SOLDOUT: "",
          HAS_AWARD: false,
          IS_ONLY_ABLY: false,
          LIST_ID: "today_recommend",
          LIST_INDEX: 5,
          CARD_TYPE: "GOODS_CARD",
        },
        inhouse: {
          goods_sno: 31315514,
          list_id: "today_recommend",
          list_index: 5,
          schema_name: "Goods",
          pool: "best",
        },
      },
      render: {
        type: "MARKET_NUDGING",
        contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
        size: "MEDIUM",
        data: {
          image: {
            url: "https://d3ha2047wt6x28.cloudfront.net/-zZT6otp0-g/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2ZmZGZhNTY4ZGU0NDRmZTYwMmMyMjA3NzZmNTNkYzQxLmdpZg",
            use_animation: true,
            ratio: 1.2,
          },
          name: "[귀여움/아방핏] 포근 후드 양털 떡볶이 퍼자켓 숏코트 덤블점퍼",
          price: "43,700",
          has_ad_badge: false,
          name_lines: 1,
          discount_rate: "15%",
          closed_reason: null,
          image_badge: null,
          image_badge_width: null,
          image_badge_height: null,
          chips: null,
          market_name: "블리즈",
          store_text: "블리즈",
          nudging_text: "3,247개 구매중",
          ranking: null,
          actions: ["LIKE"],
          discount_end_text: null,
          top_nudging_text: null,
          price_description: null,
          today_delivery_order_deadline_time: null,
        },
      },
    },
  },
  {
    type: "GOODS_CARD",
    item_entity: {
      item: {
        sno: 33198315,
        name: "(2size/기본,롱)[부함X허얇골넓🤍] made 포텐 니트 기모 슬림핏 트레이닝세트 기모트레이닝 니트트레이닝 홀리제작",
        market_sno: 7539,
        market_name: "홀리",
        image:
          "https://d3ha2047wt6x28.cloudfront.net/F9o_KRVKRc4/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzQ0M2YwMGY3MDM5YzY2YzA1NThmOWVkZGJlMDQ2NjE3LmdpZg",
        closed_reason: null,
        sell_count: 439,
        delivery_type: "standard",
        ranking: null,
        available_only_new_member: false,
        first_page_rendering: {
          goods_name:
            "(2size/기본,롱)[부함X허얇골넓🤍] made 포텐 니트 기모 슬림핏 트레이닝세트 기모트레이닝 니트트레이닝 홀리제작",
          market_name: "홀리",
          cover_image:
            "https://d3ha2047wt6x28.cloudfront.net/RZ-WY0XiH4Q/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMTA2XzE3MzA4NzQ4NTIwOTQ3OTBtLmpwZw",
          market_image:
            "https://d3ha2047wt6x28.cloudfront.net/pcfpQ83n63E/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE2NzgwNzM2NzQzOTg1MDcucG5n",
          discount_rate: 52,
          original_price: 70000,
          price: 33200,
        },
        is_premium_hotdeal: false,
        is_hotdeal: false,
        is_new: false,
        price: 33200,
        discount_rate: 52,
        like: {
          goods_sno: 33198315,
          is_liked: false,
          folder_sno: null,
          referrer: {
            list_id: "today_recommend",
            list_index: 6,
          },
        },
        ad: null,
        on_return: {
          type: "INJECT",
          data: {
            url: "goods/33198315/recommend_related_goods_by_click_for_today/?from=TODAY",
          },
        },
        market_type: "셀럽",
        category_name: "투피스",
        feedback_type: "contain_icon",
        remote_deeplink:
          "ably://goods/33198315/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%282size%2F%5Cuae30%5Cubcf8%2C%5Cub871%29%5B%5Cubd80%5Cud568X%5Cud5c8%5Cuc587%5Cuace8%5Cub113%5Cud83e%5Cudd0d%5D%20made%20%5Cud3ec%5Cud150%20%5Cub2c8%5Cud2b8%20%5Cuae30%5Cubaa8%20%5Cuc2ac%5Cub9bc%5Cud54f%20%5Cud2b8%5Cub808%5Cuc774%5Cub2dd%5Cuc138%5Cud2b8%20%5Cuae30%5Cubaa8%5Cud2b8%5Cub808%5Cuc774%5Cub2dd%20%5Cub2c8%5Cud2b8%5Cud2b8%5Cub808%5Cuc774%5Cub2dd%20%5Cud640%5Cub9ac%5Cuc81c%5Cuc791%22%2C%20%22market_name%22%3A%20%22%5Cud640%5Cub9ac%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FRZ-WY0XiH4Q%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMTA2XzE3MzA4NzQ4NTIwOTQ3OTBtLmpwZw%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FpcfpQ83n63E%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE2NzgwNzM2NzQzOTg1MDcucG5n%22%2C%20%22discount_rate%22%3A%2052%2C%20%22original_price%22%3A%2070000%2C%20%22price%22%3A%2033200%7D",
      },
      logging: {
        analytics: {
          GOODS_SNO: "33198315",
          GOODS_NAME:
            "(2size/기본,롱)[부함X허얇골넓🤍] made 포텐 니트 기모 슬림핏 트레이닝세트 기모트레이닝 니트트레이닝 홀리제작",
          MARKET_TYPE: "셀럽",
          MARKET_SNO: "7539",
          MARKET_NAME: "홀리",
          CATEGORY_SNO: "208",
          CATEGORY_NAME: "투피스",
          STANDARD_CATEGORY_SNO: "33",
          STANDARD_CATEGORY_NAME: "투피스",
          DISCOUNT_RATE: 52,
          SALES_PRICE: 33200,
          SALES_PRICE_RANGE: "30,001~35,000",
          IS_NEW: "0",
          DELIVERY_TYPE: "standard",
          IS_AD: "0",
          LIST_PARAMS: null,
          MARKET_TYPE_SNO: "7",
          REVIEW_COUNT: 0,
          REVIEW_COUNT_RANGE: "0",
          REVIEW_RATING: 0,
          LIKES_COUNT: 581,
          LIKES_COUNT_RANGE: "551~600",
          DELIVERY_SCORE: null,
          PROMOTION_TAG: [],
          UPCOMMING_SOLDOUT: "",
          HAS_AWARD: false,
          IS_ONLY_ABLY: false,
          LIST_ID: "today_recommend",
          LIST_INDEX: 6,
          CARD_TYPE: "GOODS_CARD",
        },
        inhouse: {
          goods_sno: 33198315,
          list_id: "today_recommend",
          list_index: 6,
          schema_name: "Goods",
          pool: "best",
        },
      },
      render: {
        type: "MARKET_NUDGING",
        contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
        size: "MEDIUM",
        data: {
          image: {
            url: "https://d3ha2047wt6x28.cloudfront.net/F9o_KRVKRc4/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzQ0M2YwMGY3MDM5YzY2YzA1NThmOWVkZGJlMDQ2NjE3LmdpZg",
            use_animation: true,
            ratio: 1.2,
          },
          name: "(2size/기본,롱)[부함X허얇골넓🤍] made 포텐 니트 기모 슬림핏 트레이닝세트 기모트레이닝 니트트레이닝 홀리제작",
          price: "33,200",
          has_ad_badge: false,
          name_lines: 1,
          discount_rate: "52%",
          closed_reason: null,
          image_badge: null,
          image_badge_width: null,
          image_badge_height: null,
          chips: null,
          market_name: "홀리",
          store_text: "홀리",
          nudging_text: "439개 구매중",
          ranking: null,
          actions: ["LIKE"],
          discount_end_text: null,
          top_nudging_text: null,
          price_description: null,
          today_delivery_order_deadline_time: null,
        },
      },
    },
  },
  {
    type: "GOODS_CARD",
    item_entity: {
      item: {
        sno: 31596925,
        name: "[*V넥오픈!극찬핏🐰🧶]보카시 믹스 니트 : mix color knit - 9 color",
        market_sno: 14929,
        market_name: "리즈리버",
        image:
          "https://d3ha2047wt6x28.cloudfront.net/OMT_zzSeCKg/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzMwYWRmOThjMGM4YjA5OTVlYzllZGVkOTNlZDAyYjk2LmdpZg",
        closed_reason: null,
        sell_count: 2464,
        delivery_type: "standard",
        ranking: null,
        available_only_new_member: false,
        first_page_rendering: {
          goods_name:
            "[*V넥오픈!극찬핏🐰🧶]보카시 믹스 니트 : mix color knit - 9 color",
          market_name: "리즈리버",
          cover_image:
            "https://d3ha2047wt6x28.cloudfront.net/Z7r5fYV_UdU/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDI0XzE3Mjk3NDY1OTU1ODMyNDdtLmpwZw",
          market_image:
            "https://d3ha2047wt6x28.cloudfront.net/RI8K48NgO_I/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjM2MjcxMDE4OTM4ODMuanBn",
          discount_rate: 26,
          original_price: 33000,
          price: 24410,
        },
        is_premium_hotdeal: false,
        is_hotdeal: false,
        is_new: false,
        price: 24410,
        discount_rate: 26,
        like: {
          goods_sno: 31596925,
          is_liked: false,
          folder_sno: null,
          referrer: {
            list_id: "today_recommend",
            list_index: 7,
          },
        },
        ad: null,
        on_return: {
          type: "INJECT",
          data: {
            url: "goods/31596925/recommend_related_goods_by_click_for_today/?from=TODAY",
          },
        },
        market_type: "셀럽",
        category_name: "니트",
        feedback_type: "contain_icon",
        remote_deeplink:
          "ably://goods/31596925/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5B%2AV%5Cub125%5Cuc624%5Cud508%21%5Cuadf9%5Cucc2c%5Cud54f%5Cud83d%5Cudc30%5Cud83e%5Cuddf6%5D%5Cubcf4%5Cuce74%5Cuc2dc%20%5Cubbf9%5Cuc2a4%20%5Cub2c8%5Cud2b8%20%3A%20mix%20color%20knit%20-%209%20color%22%2C%20%22market_name%22%3A%20%22%5Cub9ac%5Cuc988%5Cub9ac%5Cubc84%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FZ7r5fYV_UdU%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDI0XzE3Mjk3NDY1OTU1ODMyNDdtLmpwZw%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FRI8K48NgO_I%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjM2MjcxMDE4OTM4ODMuanBn%22%2C%20%22discount_rate%22%3A%2026%2C%20%22original_price%22%3A%2033000%2C%20%22price%22%3A%2024410%7D",
      },
      logging: {
        analytics: {
          GOODS_SNO: "31596925",
          GOODS_NAME:
            "[*V넥오픈!극찬핏🐰🧶]보카시 믹스 니트 : mix color knit - 9 color",
          MARKET_TYPE: "셀럽",
          MARKET_SNO: "14929",
          MARKET_NAME: "리즈리버",
          CATEGORY_SNO: "299",
          CATEGORY_NAME: "니트",
          STANDARD_CATEGORY_SNO: "19",
          STANDARD_CATEGORY_NAME: "니트",
          DISCOUNT_RATE: 26,
          SALES_PRICE: 24410,
          SALES_PRICE_RANGE: "20,001~25,000",
          IS_NEW: "0",
          DELIVERY_TYPE: "standard",
          IS_AD: "0",
          LIST_PARAMS: null,
          MARKET_TYPE_SNO: "7",
          REVIEW_COUNT: 31,
          REVIEW_COUNT_RANGE: "1~50",
          REVIEW_RATING: 77,
          LIKES_COUNT: 11404,
          LIKES_COUNT_RANGE: "11,401~11,450",
          DELIVERY_SCORE: null,
          PROMOTION_TAG: [],
          UPCOMMING_SOLDOUT: "",
          HAS_AWARD: false,
          IS_ONLY_ABLY: false,
          LIST_ID: "today_recommend",
          LIST_INDEX: 7,
          CARD_TYPE: "GOODS_CARD",
        },
        inhouse: {
          goods_sno: 31596925,
          list_id: "today_recommend",
          list_index: 7,
          schema_name: "Goods",
          pool: "best",
        },
      },
      render: {
        type: "MARKET_NUDGING",
        contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
        size: "MEDIUM",
        data: {
          image: {
            url: "https://d3ha2047wt6x28.cloudfront.net/OMT_zzSeCKg/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzMwYWRmOThjMGM4YjA5OTVlYzllZGVkOTNlZDAyYjk2LmdpZg",
            use_animation: true,
            ratio: 1.2,
          },
          name: "[*V넥오픈!극찬핏🐰🧶]보카시 믹스 니트 : mix color knit - 9 color",
          price: "24,410",
          has_ad_badge: false,
          name_lines: 1,
          discount_rate: "26%",
          closed_reason: null,
          image_badge: null,
          image_badge_width: null,
          image_badge_height: null,
          chips: null,
          market_name: "리즈리버",
          store_text: "리즈리버",
          nudging_text: "2,464개 구매중",
          ranking: null,
          actions: ["LIKE"],
          discount_end_text: null,
          top_nudging_text: null,
          price_description: null,
          today_delivery_order_deadline_time: null,
        },
      },
    },
  },
  {
    type: "GOODS_CARD",
    item_entity: {
      item: {
        sno: 31530345,
        name: "Made [왕따뜻] 몽블 스웨이드 차이나 크롭자켓, 집업 - 4color",
        market_sno: 2083,
        market_name: "슈가파우더",
        image:
          "https://d3ha2047wt6x28.cloudfront.net/_hubM8RMsc4/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzc2ODQwYjFmZDZlNjVjMjI4YmNlOTc2YTEzNTM5YWM2LmdpZg",
        closed_reason: null,
        sell_count: 2251,
        delivery_type: "standard",
        ranking: null,
        available_only_new_member: false,
        first_page_rendering: {
          goods_name:
            "Made [왕따뜻] 몽블 스웨이드 차이나 크롭자켓, 집업 - 4color",
          market_name: "슈가파우더",
          cover_image:
            "https://d3ha2047wt6x28.cloudfront.net/YIdZ_TdggVY/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMTAxXzE3MzA0NTIyMjEyOTUwMzNtLmpwZw",
          market_image:
            "https://d3ha2047wt6x28.cloudfront.net/AIBKojyAvVc/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE2Njk4MTYzMDE2ODUyMTkuanBn",
          discount_rate: 36,
          original_price: 68000,
          price: 43110,
        },
        is_premium_hotdeal: false,
        is_hotdeal: false,
        is_new: false,
        price: 43110,
        discount_rate: 36,
        like: {
          goods_sno: 31530345,
          is_liked: false,
          folder_sno: null,
          referrer: {
            list_id: "today_recommend",
            list_index: 8,
          },
        },
        ad: null,
        on_return: {
          type: "INJECT",
          data: {
            url: "goods/31530345/recommend_related_goods_by_click_for_today/?from=TODAY",
          },
        },
        market_type: "셀럽",
        category_name: "자켓",
        feedback_type: "contain_icon",
        remote_deeplink:
          "ably://goods/31530345/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22Made%20%5B%5Cuc655%5Cub530%5Cub73b%5D%20%5Cubabd%5Cube14%20%5Cuc2a4%5Cuc6e8%5Cuc774%5Cub4dc%20%5Cucc28%5Cuc774%5Cub098%20%5Cud06c%5Cub86d%5Cuc790%5Cucf13%2C%20%5Cuc9d1%5Cuc5c5%20-%204color%22%2C%20%22market_name%22%3A%20%22%5Cuc288%5Cuac00%5Cud30c%5Cuc6b0%5Cub354%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FYIdZ_TdggVY%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMTAxXzE3MzA0NTIyMjEyOTUwMzNtLmpwZw%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FAIBKojyAvVc%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE2Njk4MTYzMDE2ODUyMTkuanBn%22%2C%20%22discount_rate%22%3A%2036%2C%20%22original_price%22%3A%2068000%2C%20%22price%22%3A%2043110%7D",
      },
      logging: {
        analytics: {
          GOODS_SNO: "31530345",
          GOODS_NAME:
            "Made [왕따뜻] 몽블 스웨이드 차이나 크롭자켓, 집업 - 4color",
          MARKET_TYPE: "셀럽",
          MARKET_SNO: "2083",
          MARKET_NAME: "슈가파우더",
          CATEGORY_SNO: "293",
          CATEGORY_NAME: "자켓",
          STANDARD_CATEGORY_SNO: "4",
          STANDARD_CATEGORY_NAME: "자켓",
          DISCOUNT_RATE: 36,
          SALES_PRICE: 43110,
          SALES_PRICE_RANGE: "40,001~45,000",
          IS_NEW: "0",
          DELIVERY_TYPE: "standard",
          IS_AD: "0",
          LIST_PARAMS: null,
          MARKET_TYPE_SNO: "7",
          REVIEW_COUNT: 10,
          REVIEW_COUNT_RANGE: "1~50",
          REVIEW_RATING: 100,
          LIKES_COUNT: 8076,
          LIKES_COUNT_RANGE: "8,051~8,100",
          DELIVERY_SCORE: null,
          PROMOTION_TAG: [],
          UPCOMMING_SOLDOUT: "",
          HAS_AWARD: false,
          IS_ONLY_ABLY: false,
          LIST_ID: "today_recommend",
          LIST_INDEX: 8,
          CARD_TYPE: "GOODS_CARD",
        },
        inhouse: {
          goods_sno: 31530345,
          list_id: "today_recommend",
          list_index: 8,
          schema_name: "Goods",
          pool: "best",
        },
      },
      render: {
        type: "MARKET_NUDGING",
        contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
        size: "MEDIUM",
        data: {
          image: {
            url: "https://d3ha2047wt6x28.cloudfront.net/_hubM8RMsc4/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzc2ODQwYjFmZDZlNjVjMjI4YmNlOTc2YTEzNTM5YWM2LmdpZg",
            use_animation: true,
            ratio: 1.2,
          },
          name: "Made [왕따뜻] 몽블 스웨이드 차이나 크롭자켓, 집업 - 4color",
          price: "43,110",
          has_ad_badge: false,
          name_lines: 1,
          discount_rate: "36%",
          closed_reason: null,
          image_badge: null,
          image_badge_width: null,
          image_badge_height: null,
          chips: null,
          market_name: "슈가파우더",
          store_text: "슈가파우더",
          nudging_text: "2,251개 구매중",
          ranking: null,
          actions: ["LIKE"],
          discount_end_text: null,
          top_nudging_text: null,
          price_description: null,
          today_delivery_order_deadline_time: null,
        },
      },
    },
  },
  {
    type: "GOODS_CARD",
    item_entity: {
      item: {
        sno: 30433969,
        name: "[ONLY ABLY💘][무조건 20% 쿠폰✨]헤프 하이넥 시그니처 웰론 패딩 남녀공용 (7컬러)",
        market_sno: 64043,
        market_name: "무센트",
        image:
          "https://d3ha2047wt6x28.cloudfront.net/4JrIK_qJCm0/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzFiOTY5Y2I1NTEwMmFhNmM4ZDJmZDE1N2NlZTBlNDdmLmdpZg",
        closed_reason: null,
        sell_count: 2273,
        delivery_type: "standard",
        ranking: null,
        available_only_new_member: false,
        first_page_rendering: {
          goods_name:
            "[ONLY ABLY💘][무조건 20% 쿠폰✨]헤프 하이넥 시그니처 웰론 패딩 남녀공용 (7컬러)",
          market_name: null,
          cover_image:
            "https://d3ha2047wt6x28.cloudfront.net/bjl1pB-d2GA/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDI4XzE3MzAwNzk5Njk1NDMwMzNtLnBuZw",
          market_image: null,
          discount_rate: 49,
          original_price: 213900,
          price: 109000,
        },
        is_premium_hotdeal: false,
        is_hotdeal: false,
        is_new: false,
        price: 109000,
        discount_rate: 49,
        like: {
          goods_sno: 30433969,
          is_liked: false,
          folder_sno: null,
          referrer: {
            list_id: "today_recommend",
            list_index: 9,
          },
        },
        ad: null,
        on_return: {
          type: "INJECT",
          data: {
            url: "goods/30433969/recommend_related_goods_by_click_for_today/?from=TODAY",
          },
        },
        market_type: "스트릿 브랜드",
        category_name: "패딩",
        feedback_type: "contain_icon",
        remote_deeplink:
          "ably://goods/30433969/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5BONLY%20ABLY%5Cud83d%5Cudc98%5D%5B%5Cubb34%5Cuc870%5Cuac74%2020%25%20%5Cucfe0%5Cud3f0%5Cu2728%5D%5Cud5e4%5Cud504%20%5Cud558%5Cuc774%5Cub125%20%5Cuc2dc%5Cuadf8%5Cub2c8%5Cucc98%20%5Cuc6f0%5Cub860%20%5Cud328%5Cub529%20%5Cub0a8%5Cub140%5Cuacf5%5Cuc6a9%20%287%5Cuceec%5Cub7ec%29%22%2C%20%22market_name%22%3A%20null%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2Fbjl1pB-d2GA%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDI4XzE3MzAwNzk5Njk1NDMwMzNtLnBuZw%22%2C%20%22market_image%22%3A%20null%2C%20%22discount_rate%22%3A%2049%2C%20%22original_price%22%3A%20213900%2C%20%22price%22%3A%20109000%7D",
      },
      logging: {
        analytics: {
          GOODS_SNO: "30433969",
          GOODS_NAME:
            "[ONLY ABLY💘][무조건 20% 쿠폰✨]헤프 하이넥 시그니처 웰론 패딩 남녀공용 (7컬러)",
          MARKET_TYPE: "스트릿 브랜드",
          MARKET_SNO: "64043",
          MARKET_NAME: "무센트",
          CATEGORY_SNO: "297",
          CATEGORY_NAME: "패딩",
          STANDARD_CATEGORY_SNO: "9",
          STANDARD_CATEGORY_NAME: "패딩",
          DISCOUNT_RATE: 49,
          SALES_PRICE: 109000,
          SALES_PRICE_RANGE: "105,001~110,000",
          IS_NEW: "0",
          DELIVERY_TYPE: "standard",
          IS_AD: "0",
          LIST_PARAMS: null,
          MARKET_TYPE_SNO: "11",
          REVIEW_COUNT: 21,
          REVIEW_COUNT_RANGE: "1~50",
          REVIEW_RATING: 100,
          LIKES_COUNT: 9435,
          LIKES_COUNT_RANGE: "9,401~9,450",
          DELIVERY_SCORE: null,
          PROMOTION_TAG: ["BRAND"],
          UPCOMMING_SOLDOUT: "",
          HAS_AWARD: false,
          IS_ONLY_ABLY: false,
          LIST_ID: "today_recommend",
          LIST_INDEX: 9,
          BRAND_SNO: 14035,
          BRAND_NAME: "무센트",
          CARD_TYPE: "GOODS_CARD",
        },
        inhouse: {
          goods_sno: 30433969,
          list_id: "today_recommend",
          list_index: 9,
          schema_name: "Goods",
          pool: "best",
        },
      },
      render: {
        type: "MARKET_NUDGING_CHIPS",
        contents: ["PRICE", "NAME", "MARKET", "NUDGING", "CHIPS"],
        size: "MEDIUM",
        data: {
          image: {
            url: "https://d3ha2047wt6x28.cloudfront.net/4JrIK_qJCm0/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzFiOTY5Y2I1NTEwMmFhNmM4ZDJmZDE1N2NlZTBlNDdmLmdpZg",
            use_animation: true,
            ratio: 1.2,
          },
          name: "[ONLY ABLY💘][무조건 20% 쿠폰✨]헤프 하이넥 시그니처 웰론 패딩 남녀공용 (7컬러)",
          price: "109,000",
          has_ad_badge: false,
          name_lines: 1,
          discount_rate: "49%",
          closed_reason: null,
          image_badge: null,
          image_badge_width: null,
          image_badge_height: null,
          chips: [
            {
              type: "BRAND",
              name: "브랜드",
            },
          ],
          market_name: "무센트",
          store_text: "<font color='#6093FC'>브랜드</font> 무센트",
          nudging_text: "2,273개 구매중",
          ranking: null,
          actions: ["LIKE"],
          discount_end_text: null,
          top_nudging_text: null,
          price_description: null,
          today_delivery_order_deadline_time: null,
        },
      },
    },
  },
  {
    type: "GOODS_CARD",
    item_entity: {
      item: {
        sno: 12382707,
        name: "[신상할인/러블리🤎🧸] 이중 덤블 더플 떡볶이 뽀글이 누빔 패딩 -2color",
        market_sno: 1162,
        market_name: "모디무드",
        image:
          "https://d3ha2047wt6x28.cloudfront.net/6eNW690bRn8/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzhmZDZlYmMxY2I4ZjU1MTAwYTFhOTNiNTYyMzUxMWVlLmdpZg",
        closed_reason: null,
        sell_count: 10968,
        delivery_type: "standard",
        ranking: null,
        available_only_new_member: false,
        first_page_rendering: {
          goods_name:
            "[신상할인/러블리🤎🧸] 이중 덤블 더플 떡볶이 뽀글이 누빔 패딩 -2color",
          market_name: "모디무드",
          cover_image:
            "https://d3ha2047wt6x28.cloudfront.net/R4uHrLKT_64/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzFmZDBmNmNmMDZjYzhlYjc5OGIyOTNmYzEyZGYzNWM4LmdpZg",
          market_image:
            "https://d3ha2047wt6x28.cloudfront.net/I5wVeFi1Bqk/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjkwNDU1OTIyMTkxMjIuanBlZw",
          discount_rate: 11,
          original_price: 65000,
          price: 57470,
        },
        is_premium_hotdeal: false,
        is_hotdeal: false,
        is_new: false,
        price: 57470,
        discount_rate: 11,
        like: {
          goods_sno: 12382707,
          is_liked: false,
          folder_sno: null,
          referrer: {
            list_id: "today_recommend",
            list_index: 10,
          },
        },
        ad: null,
        on_return: {
          type: "INJECT",
          data: {
            url: "goods/12382707/recommend_related_goods_by_click_for_today/?from=TODAY",
          },
        },
        market_type: "쇼핑몰",
        category_name: "집업/점퍼",
        feedback_type: "contain_icon",
        remote_deeplink:
          "ably://goods/12382707/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5B%5Cuc2e0%5Cuc0c1%5Cud560%5Cuc778%2F%5Cub7ec%5Cube14%5Cub9ac%5Cud83e%5Cudd0e%5Cud83e%5Cuddf8%5D%20%5Cuc774%5Cuc911%20%5Cub364%5Cube14%20%5Cub354%5Cud50c%20%5Cub5a1%5Cubcf6%5Cuc774%20%5Cubf40%5Cuae00%5Cuc774%20%5Cub204%5Cube54%20%5Cud328%5Cub529%20-2color%22%2C%20%22market_name%22%3A%20%22%5Cubaa8%5Cub514%5Cubb34%5Cub4dc%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FR4uHrLKT_64%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzFmZDBmNmNmMDZjYzhlYjc5OGIyOTNmYzEyZGYzNWM4LmdpZg%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FI5wVeFi1Bqk%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjkwNDU1OTIyMTkxMjIuanBlZw%22%2C%20%22discount_rate%22%3A%2011%2C%20%22original_price%22%3A%2065000%2C%20%22price%22%3A%2057470%7D",
      },
      logging: {
        analytics: {
          GOODS_SNO: "12382707",
          GOODS_NAME:
            "[신상할인/러블리🤎🧸] 이중 덤블 더플 떡볶이 뽀글이 누빔 패딩 -2color",
          MARKET_TYPE: "쇼핑몰",
          MARKET_SNO: "1162",
          MARKET_NAME: "모디무드",
          CATEGORY_SNO: "294",
          CATEGORY_NAME: "집업/점퍼",
          STANDARD_CATEGORY_SNO: "7",
          STANDARD_CATEGORY_NAME: "점퍼",
          DISCOUNT_RATE: 11,
          SALES_PRICE: 57470,
          SALES_PRICE_RANGE: "55,001~60,000",
          IS_NEW: "0",
          DELIVERY_TYPE: "today",
          IS_AD: "0",
          LIST_PARAMS: null,
          MARKET_TYPE_SNO: "8",
          REVIEW_COUNT: 467,
          REVIEW_COUNT_RANGE: "451~500",
          REVIEW_RATING: 95,
          LIKES_COUNT: 50686,
          LIKES_COUNT_RANGE: "50,651~50,700",
          DELIVERY_SCORE: null,
          PROMOTION_TAG: [],
          UPCOMMING_SOLDOUT: "",
          HAS_AWARD: false,
          IS_ONLY_ABLY: false,
          LIST_ID: "today_recommend",
          LIST_INDEX: 10,
          CARD_TYPE: "GOODS_CARD",
        },
        inhouse: {
          goods_sno: 12382707,
          list_id: "today_recommend",
          list_index: 10,
          schema_name: "Goods",
          pool: "best",
        },
      },
      render: {
        type: "MARKET_NUDGING",
        contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
        size: "MEDIUM",
        data: {
          image: {
            url: "https://d3ha2047wt6x28.cloudfront.net/6eNW690bRn8/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzhmZDZlYmMxY2I4ZjU1MTAwYTFhOTNiNTYyMzUxMWVlLmdpZg",
            use_animation: true,
            ratio: 1.2,
          },
          name: "[신상할인/러블리🤎🧸] 이중 덤블 더플 떡볶이 뽀글이 누빔 패딩 -2color",
          price: "57,470",
          has_ad_badge: false,
          name_lines: 1,
          discount_rate: "11%",
          closed_reason: null,
          image_badge: null,
          image_badge_width: null,
          image_badge_height: null,
          chips: null,
          market_name: "모디무드",
          store_text: "모디무드",
          nudging_text: "10,968개 구매중",
          ranking: null,
          actions: ["LIKE"],
          discount_end_text: null,
          top_nudging_text: null,
          price_description: null,
          today_delivery_order_deadline_time: null,
        },
      },
    },
  },
  {
    type: "GOODS_CARD",
    item_entity: {
      item: {
        sno: 32375640,
        name: "[의약외품] 셀프 치아미백제 1개",
        market_sno: 76585,
        market_name: "구스투스",
        image:
          "https://d3ha2047wt6x28.cloudfront.net/vdBXPll2T0o/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzk3ZmZiYTk4NThjN2FlOTZkZGI1MzQ2NTEyYjczMDI4LmpwZw",
        closed_reason: null,
        sell_count: 1374,
        delivery_type: "standard",
        ranking: null,
        available_only_new_member: false,
        first_page_rendering: {
          goods_name: "[의약외품] 셀프 치아미백제 1개",
          market_name: null,
          cover_image:
            "https://d3ha2047wt6x28.cloudfront.net/weWv8GfDFzI/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDMwXzE3MzAyNzQ4MjgzOTAwNTNtLmpwZw",
          market_image: null,
          discount_rate: 27,
          original_price: 22000,
          price: 15900,
        },
        is_premium_hotdeal: false,
        is_hotdeal: false,
        is_new: false,
        price: 15900,
        discount_rate: 27,
        like: {
          goods_sno: 32375640,
          is_liked: false,
          folder_sno: null,
          referrer: {
            list_id: "today_recommend",
            list_index: 11,
          },
        },
        ad: null,
        on_return: {
          type: "INJECT",
          data: {
            url: "goods/32375640/recommend_related_goods_by_click_for_today/?from=TODAY",
          },
        },
        market_type: "뷰티",
        category_name: "기타메이크업 소품",
        feedback_type: "contain_icon",
        remote_deeplink:
          "ably://goods/32375640/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5B%5Cuc758%5Cuc57d%5Cuc678%5Cud488%5D%20%5Cuc140%5Cud504%20%5Cuce58%5Cuc544%5Cubbf8%5Cubc31%5Cuc81c%201%5Cuac1c%22%2C%20%22market_name%22%3A%20null%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FweWv8GfDFzI%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDMwXzE3MzAyNzQ4MjgzOTAwNTNtLmpwZw%22%2C%20%22market_image%22%3A%20null%2C%20%22discount_rate%22%3A%2027%2C%20%22original_price%22%3A%2022000%2C%20%22price%22%3A%2015900%7D",
      },
      logging: {
        analytics: {
          GOODS_SNO: "32375640",
          GOODS_NAME: "[의약외품] 셀프 치아미백제 1개",
          MARKET_TYPE: "뷰티",
          MARKET_SNO: "76585",
          MARKET_NAME: "구스투스",
          CATEGORY_SNO: "643",
          CATEGORY_NAME: "기타메이크업 소품",
          STANDARD_CATEGORY_SNO: "454",
          STANDARD_CATEGORY_NAME: "기타메이크업 소품",
          DISCOUNT_RATE: 27,
          SALES_PRICE: 15900,
          SALES_PRICE_RANGE: "15,001~20,000",
          IS_NEW: "0",
          DELIVERY_TYPE: "standard",
          IS_AD: "0",
          LIST_PARAMS: null,
          MARKET_TYPE_SNO: "3",
          REVIEW_COUNT: 10,
          REVIEW_COUNT_RANGE: "1~50",
          REVIEW_RATING: 100,
          LIKES_COUNT: 7642,
          LIKES_COUNT_RANGE: "7,601~7,650",
          DELIVERY_SCORE: null,
          PROMOTION_TAG: [],
          UPCOMMING_SOLDOUT: "",
          HAS_AWARD: false,
          IS_ONLY_ABLY: false,
          LIST_ID: "today_recommend",
          LIST_INDEX: 11,
          BRAND_SNO: 15701,
          BRAND_NAME: "구스투스",
          CARD_TYPE: "GOODS_CARD",
        },
        inhouse: {
          goods_sno: 32375640,
          list_id: "today_recommend",
          list_index: 11,
          schema_name: "Goods",
          pool: "best",
        },
      },
      render: {
        type: "MARKET_NUDGING",
        contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
        size: "MEDIUM",
        data: {
          image: {
            url: "https://d3ha2047wt6x28.cloudfront.net/vdBXPll2T0o/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzk3ZmZiYTk4NThjN2FlOTZkZGI1MzQ2NTEyYjczMDI4LmpwZw",
            use_animation: true,
            ratio: 1.2,
          },
          name: "[의약외품] 셀프 치아미백제 1개",
          price: "15,900",
          has_ad_badge: false,
          name_lines: 1,
          discount_rate: "27%",
          closed_reason: null,
          image_badge: null,
          image_badge_width: null,
          image_badge_height: null,
          chips: null,
          market_name: "구스투스",
          store_text: "구스투스",
          nudging_text: "1,374개 구매중",
          ranking: null,
          actions: ["LIKE"],
          discount_end_text: null,
          top_nudging_text: null,
          price_description: null,
          today_delivery_order_deadline_time: null,
        },
      },
    },
  },
  {
    type: "GOODS_CARD",
    item_entity: {
      item: {
        sno: 32364107,
        name: "[예약주문][자체제작] 에끌레르 울70% 핸드메이드 코트 숏ver. -3 color (가을신상/겨울신상/하프/키작녀/아담녀/fw/허리끈/절개/스트랩/단추/긴팔)",
        market_sno: 6092,
        market_name: "히니크",
        image:
          "https://d3ha2047wt6x28.cloudfront.net/WjL7uvL62r0/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzc1YTc3ZWE5YjAwZmFiZTljOWUwZmFmOTc4OTllOWRmLmdpZg",
        closed_reason: null,
        sell_count: 824,
        delivery_type: "reserved",
        ranking: null,
        available_only_new_member: false,
        first_page_rendering: {
          goods_name:
            "[예약주문][자체제작] 에끌레르 울70% 핸드메이드 코트 숏ver. -3 color (가을신상/겨울신상/하프/키작녀/아담녀/fw/허리끈/절개/스트랩/단추/긴팔)",
          market_name: "히니크",
          cover_image:
            "https://d3ha2047wt6x28.cloudfront.net/nMji5f51a2I/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDMwXzE3MzAyNTgyOTA1NjAyNTZtLmpwZw",
          market_image:
            "https://d3ha2047wt6x28.cloudfront.net/bii5Pd_RnE0/pr:MARKET_PROFILE_THUMB/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjkwNDE3MzE3NTY5NTQuanBn",
          discount_rate: 7,
          original_price: 191500,
          price: 178090,
        },
        is_premium_hotdeal: false,
        is_hotdeal: false,
        is_new: false,
        price: 178090,
        discount_rate: 7,
        like: {
          goods_sno: 32364107,
          is_liked: false,
          folder_sno: null,
          referrer: {
            list_id: "today_recommend",
            list_index: 12,
          },
        },
        ad: null,
        on_return: {
          type: "INJECT",
          data: {
            url: "goods/32364107/recommend_related_goods_by_click_for_today/?from=TODAY",
          },
        },
        market_type: "쇼핑몰",
        category_name: "코트",
        feedback_type: "contain_icon",
        remote_deeplink:
          "ably://goods/32364107/?list_id=today_recommend&logging_analytics=%7B%22FROM%22%3A%20%22TODAY%22%7D&first_page_rendering=%7B%22goods_name%22%3A%20%22%5B%5Cuc608%5Cuc57d%5Cuc8fc%5Cubb38%5D%5B%5Cuc790%5Cuccb4%5Cuc81c%5Cuc791%5D%20%5Cuc5d0%5Cub04c%5Cub808%5Cub974%20%5Cuc6b870%25%20%5Cud578%5Cub4dc%5Cuba54%5Cuc774%5Cub4dc%20%5Cucf54%5Cud2b8%20%5Cuc20fver.%20-3%20color%20%28%5Cuac00%5Cuc744%5Cuc2e0%5Cuc0c1%2F%5Cuaca8%5Cuc6b8%5Cuc2e0%5Cuc0c1%2F%5Cud558%5Cud504%2F%5Cud0a4%5Cuc791%5Cub140%2F%5Cuc544%5Cub2f4%5Cub140%2Ffw%2F%5Cud5c8%5Cub9ac%5Cub048%2F%5Cuc808%5Cuac1c%2F%5Cuc2a4%5Cud2b8%5Cub7a9%2F%5Cub2e8%5Cucd94%2F%5Cuae34%5Cud314%29%22%2C%20%22market_name%22%3A%20%22%5Cud788%5Cub2c8%5Cud06c%22%2C%20%22cover_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2FnMji5f51a2I%2Fpr%3AGOODS_DETAIL%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDMwXzE3MzAyNTgyOTA1NjAyNTZtLmpwZw%22%2C%20%22market_image%22%3A%20%22https%3A%2F%2Fd3ha2047wt6x28.cloudfront.net%2Fbii5Pd_RnE0%2Fpr%3AMARKET_PROFILE_THUMB%2FczM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2JyYW5kX2NhdGVnb3J5L21hcmtldF9wcm9maWxlXzE3MjkwNDE3MzE3NTY5NTQuanBn%22%2C%20%22discount_rate%22%3A%207%2C%20%22original_price%22%3A%20191500%2C%20%22price%22%3A%20178090%7D",
      },
      logging: {
        analytics: {
          GOODS_SNO: "32364107",
          GOODS_NAME:
            "[예약주문][자체제작] 에끌레르 울70% 핸드메이드 코트 숏ver. -3 color (가을신상/겨울신상/하프/키작녀/아담녀/fw/허리끈/절개/스트랩/단추/긴팔)",
          MARKET_TYPE: "쇼핑몰",
          MARKET_SNO: "6092",
          MARKET_NAME: "히니크",
          CATEGORY_SNO: "296",
          CATEGORY_NAME: "코트",
          STANDARD_CATEGORY_SNO: "8",
          STANDARD_CATEGORY_NAME: "코트",
          DISCOUNT_RATE: 7,
          SALES_PRICE: 178090,
          SALES_PRICE_RANGE: "175,001~180,000",
          IS_NEW: "0",
          DELIVERY_TYPE: "reserved",
          IS_AD: "0",
          LIST_PARAMS: null,
          MARKET_TYPE_SNO: "8",
          REVIEW_COUNT: 0,
          REVIEW_COUNT_RANGE: "0",
          REVIEW_RATING: 0,
          LIKES_COUNT: 3601,
          LIKES_COUNT_RANGE: "3,601~3,650",
          DELIVERY_SCORE: null,
          PROMOTION_TAG: [],
          UPCOMMING_SOLDOUT: "",
          HAS_AWARD: false,
          IS_ONLY_ABLY: false,
          LIST_ID: "today_recommend",
          LIST_INDEX: 12,
          CARD_TYPE: "GOODS_CARD",
        },
        inhouse: {
          goods_sno: 32364107,
          list_id: "today_recommend",
          list_index: 12,
          schema_name: "Goods",
          pool: "best",
        },
      },
      render: {
        type: "MARKET_NUDGING",
        contents: ["PRICE", "NAME", "MARKET", "NUDGING"],
        size: "MEDIUM",
        data: {
          image: {
            url: "https://d3ha2047wt6x28.cloudfront.net/WjL7uvL62r0/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzc1YTc3ZWE5YjAwZmFiZTljOWUwZmFmOTc4OTllOWRmLmdpZg",
            use_animation: true,
            ratio: 1.2,
          },
          name: "[예약주문][자체제작] 에끌레르 울70% 핸드메이드 코트 숏ver. -3 color (가을신상/겨울신상/하프/키작녀/아담녀/fw/허리끈/절개/스트랩/단추/긴팔)",
          price: "178,090",
          has_ad_badge: false,
          name_lines: 1,
          discount_rate: "7%",
          closed_reason: null,
          image_badge:
            "https://d3ha2047wt6x28.cloudfront.net/Pr4lELVaLck/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfcmVzZXJ2ZWRfZGVsaXZlcnkucG5n",
          image_badge_width: 46,
          image_badge_height: 18,
          chips: null,
          market_name: "히니크",
          store_text: "히니크",
          nudging_text: "824개 구매중",
          ranking: null,
          actions: ["LIKE"],
          discount_end_text: null,
          top_nudging_text: null,
          price_description: null,
          today_delivery_order_deadline_time: null,
        },
      },
    },
  },
];
